// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/third/carousel.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CarouselInfo struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64        `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64        `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string       `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string       `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string       `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string       `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Quotes               []*QuoteInfo `protobuf:"bytes,31,rep,name=quotes,proto3" json:"quotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CarouselInfo) Reset()         { *m = CarouselInfo{} }
func (m *CarouselInfo) String() string { return proto.CompactTextString(m) }
func (*CarouselInfo) ProtoMessage()    {}
func (*CarouselInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1f10fd87ffa936, []int{0}
}

func (m *CarouselInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarouselInfo.Unmarshal(m, b)
}
func (m *CarouselInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarouselInfo.Marshal(b, m, deterministic)
}
func (m *CarouselInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarouselInfo.Merge(m, src)
}
func (m *CarouselInfo) XXX_Size() int {
	return xxx_messageInfo_CarouselInfo.Size(m)
}
func (m *CarouselInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CarouselInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CarouselInfo proto.InternalMessageInfo

func (m *CarouselInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CarouselInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CarouselInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CarouselInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *CarouselInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CarouselInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *CarouselInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CarouselInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CarouselInfo) GetQuotes() []*QuoteInfo {
	if m != nil {
		return m.Quotes
	}
	return nil
}

type QuoteInfo struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Updated              int64    `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Asset                string   `protobuf:"bytes,5,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuoteInfo) Reset()         { *m = QuoteInfo{} }
func (m *QuoteInfo) String() string { return proto.CompactTextString(m) }
func (*QuoteInfo) ProtoMessage()    {}
func (*QuoteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1f10fd87ffa936, []int{1}
}

func (m *QuoteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuoteInfo.Unmarshal(m, b)
}
func (m *QuoteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuoteInfo.Marshal(b, m, deterministic)
}
func (m *QuoteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuoteInfo.Merge(m, src)
}
func (m *QuoteInfo) XXX_Size() int {
	return xxx_messageInfo_QuoteInfo.Size(m)
}
func (m *QuoteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_QuoteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_QuoteInfo proto.InternalMessageInfo

func (m *QuoteInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *QuoteInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *QuoteInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *QuoteInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *QuoteInfo) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type ReqCarouselAdd struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string       `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Remark               string       `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string       `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Quotes               []*QuoteInfo `protobuf:"bytes,21,rep,name=quotes,proto3" json:"quotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqCarouselAdd) Reset()         { *m = ReqCarouselAdd{} }
func (m *ReqCarouselAdd) String() string { return proto.CompactTextString(m) }
func (*ReqCarouselAdd) ProtoMessage()    {}
func (*ReqCarouselAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1f10fd87ffa936, []int{2}
}

func (m *ReqCarouselAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCarouselAdd.Unmarshal(m, b)
}
func (m *ReqCarouselAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCarouselAdd.Marshal(b, m, deterministic)
}
func (m *ReqCarouselAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCarouselAdd.Merge(m, src)
}
func (m *ReqCarouselAdd) XXX_Size() int {
	return xxx_messageInfo_ReqCarouselAdd.Size(m)
}
func (m *ReqCarouselAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCarouselAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCarouselAdd proto.InternalMessageInfo

func (m *ReqCarouselAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCarouselAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqCarouselAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqCarouselAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqCarouselAdd) GetQuotes() []*QuoteInfo {
	if m != nil {
		return m.Quotes
	}
	return nil
}

type ReqCarouselUpdate struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Operator             string       `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Quotes               []*QuoteInfo `protobuf:"bytes,21,rep,name=quotes,proto3" json:"quotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqCarouselUpdate) Reset()         { *m = ReqCarouselUpdate{} }
func (m *ReqCarouselUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqCarouselUpdate) ProtoMessage()    {}
func (*ReqCarouselUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1f10fd87ffa936, []int{3}
}

func (m *ReqCarouselUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCarouselUpdate.Unmarshal(m, b)
}
func (m *ReqCarouselUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCarouselUpdate.Marshal(b, m, deterministic)
}
func (m *ReqCarouselUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCarouselUpdate.Merge(m, src)
}
func (m *ReqCarouselUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqCarouselUpdate.Size(m)
}
func (m *ReqCarouselUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCarouselUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCarouselUpdate proto.InternalMessageInfo

func (m *ReqCarouselUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqCarouselUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCarouselUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqCarouselUpdate) GetQuotes() []*QuoteInfo {
	if m != nil {
		return m.Quotes
	}
	return nil
}

type ReplyCarouselInfo struct {
	Info                 *CarouselInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyCarouselInfo) Reset()         { *m = ReplyCarouselInfo{} }
func (m *ReplyCarouselInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyCarouselInfo) ProtoMessage()    {}
func (*ReplyCarouselInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1f10fd87ffa936, []int{4}
}

func (m *ReplyCarouselInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyCarouselInfo.Unmarshal(m, b)
}
func (m *ReplyCarouselInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyCarouselInfo.Marshal(b, m, deterministic)
}
func (m *ReplyCarouselInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyCarouselInfo.Merge(m, src)
}
func (m *ReplyCarouselInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyCarouselInfo.Size(m)
}
func (m *ReplyCarouselInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyCarouselInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyCarouselInfo proto.InternalMessageInfo

func (m *ReplyCarouselInfo) GetInfo() *CarouselInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyCarouselInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyCarouselList struct {
	Status               *ReplyStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32          `protobuf:"varint,3,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32          `protobuf:"varint,4,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*CarouselInfo `protobuf:"bytes,21,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReplyCarouselList) Reset()         { *m = ReplyCarouselList{} }
func (m *ReplyCarouselList) String() string { return proto.CompactTextString(m) }
func (*ReplyCarouselList) ProtoMessage()    {}
func (*ReplyCarouselList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d1f10fd87ffa936, []int{5}
}

func (m *ReplyCarouselList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyCarouselList.Unmarshal(m, b)
}
func (m *ReplyCarouselList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyCarouselList.Marshal(b, m, deterministic)
}
func (m *ReplyCarouselList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyCarouselList.Merge(m, src)
}
func (m *ReplyCarouselList) XXX_Size() int {
	return xxx_messageInfo_ReplyCarouselList.Size(m)
}
func (m *ReplyCarouselList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyCarouselList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyCarouselList proto.InternalMessageInfo

func (m *ReplyCarouselList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyCarouselList) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyCarouselList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyCarouselList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyCarouselList) GetList() []*CarouselInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*CarouselInfo)(nil), "omo.msp.third.CarouselInfo")
	proto.RegisterType((*QuoteInfo)(nil), "omo.msp.third.QuoteInfo")
	proto.RegisterType((*ReqCarouselAdd)(nil), "omo.msp.third.ReqCarouselAdd")
	proto.RegisterType((*ReqCarouselUpdate)(nil), "omo.msp.third.ReqCarouselUpdate")
	proto.RegisterType((*ReplyCarouselInfo)(nil), "omo.msp.third.ReplyCarouselInfo")
	proto.RegisterType((*ReplyCarouselList)(nil), "omo.msp.third.ReplyCarouselList")
}

func init() {
	proto.RegisterFile("proto/third/carousel.proto", fileDescriptor_1d1f10fd87ffa936)
}

var fileDescriptor_1d1f10fd87ffa936 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x7f, 0xea, 0x36, 0x93, 0xa6, 0xc0, 0xaa, 0x20, 0x2b, 0x50, 0x61, 0xf9, 0x94, 0x53,
	0x8a, 0xc2, 0x13, 0xb4, 0x95, 0x08, 0x05, 0xda, 0x52, 0x57, 0x5c, 0xb8, 0x99, 0x78, 0x5a, 0x56,
	0xd8, 0x5e, 0xd7, 0x5e, 0x37, 0xcd, 0x13, 0xf0, 0x1a, 0x3c, 0x0b, 0x0f, 0x05, 0x57, 0xb4, 0xe3,
	0x75, 0xea, 0xa4, 0x49, 0x13, 0x89, 0x9b, 0xbf, 0x99, 0xd9, 0x6f, 0xbf, 0xef, 0xdb, 0x89, 0x02,
	0xdd, 0x2c, 0x17, 0x52, 0x1c, 0xc8, 0xef, 0x3c, 0x8f, 0x0e, 0x46, 0x61, 0x2e, 0xca, 0x02, 0xe3,
	0x3e, 0x15, 0x59, 0x47, 0x24, 0xa2, 0x9f, 0x14, 0x59, 0x9f, 0xba, 0x5d, 0x77, 0x66, 0x54, 0x24,
	0x89, 0x48, 0xab, 0x41, 0xff, 0x8f, 0x01, 0x3b, 0xc7, 0xfa, 0xec, 0x49, 0x7a, 0x25, 0xd8, 0x53,
	0xb0, 0x4a, 0x1e, 0xb9, 0x86, 0x67, 0xf4, 0x5a, 0x81, 0xfa, 0x64, 0xbb, 0x60, 0xf2, 0xc8, 0x35,
	0x3d, 0xa3, 0x67, 0x07, 0x26, 0x8f, 0x98, 0x0b, 0x5b, 0xa3, 0x1c, 0x43, 0x89, 0x91, 0x6b, 0x79,
	0x46, 0xcf, 0x0a, 0x6a, 0xa8, 0x3a, 0x65, 0x16, 0x51, 0xc7, 0xae, 0x3a, 0x1a, 0x4e, 0xcf, 0x88,
	0xdc, 0xdd, 0x24, 0xe6, 0x1a, 0xb2, 0x2e, 0x6c, 0x8b, 0x0c, 0x73, 0x6a, 0x39, 0xd4, 0x9a, 0x62,
	0xc6, 0xc0, 0x4e, 0xc3, 0x04, 0xdd, 0x2d, 0xaa, 0xd3, 0x37, 0xdb, 0x83, 0x4d, 0x31, 0x4e, 0x31,
	0x77, 0xb7, 0xa9, 0x58, 0x01, 0xf6, 0x06, 0x9c, 0x9b, 0x52, 0x48, 0x2c, 0xdc, 0xd7, 0x9e, 0xd5,
	0x6b, 0x0f, 0xdc, 0xfe, 0x4c, 0x00, 0xfd, 0x0b, 0xd5, 0x54, 0xfe, 0x02, 0x3d, 0xe7, 0x8f, 0xa1,
	0x35, 0x2d, 0xaa, 0x8b, 0xe4, 0x24, 0x43, 0x72, 0xdd, 0x09, 0xe8, 0xbb, 0x69, 0xc6, 0x9c, 0x35,
	0xa3, 0x23, 0xb2, 0xee, 0x23, 0xda, 0x83, 0x4d, 0xc9, 0x65, 0x8c, 0x64, 0xbb, 0x15, 0x54, 0x40,
	0x55, 0xc3, 0xa2, 0x40, 0xa9, 0x2d, 0x57, 0xc0, 0xff, 0x65, 0xc0, 0x6e, 0x80, 0x37, 0x75, 0xe8,
	0x87, 0x51, 0x34, 0xf5, 0x69, 0x2c, 0xf2, 0x69, 0x36, 0x7d, 0xbe, 0x00, 0x27, 0xc7, 0x24, 0xcc,
	0x7f, 0xe8, 0xdb, 0x35, 0x9a, 0x49, 0xd1, 0x9e, 0x4b, 0xf1, 0x3e, 0x9b, 0xe7, 0x6b, 0x66, 0xf3,
	0xd3, 0x80, 0x67, 0x0d, 0x89, 0x5f, 0xc8, 0xf7, 0x82, 0xcd, 0xa8, 0x75, 0x9b, 0x0d, 0xdd, 0x4d,
	0x25, 0xd6, 0x7f, 0x2b, 0xb9, 0x53, 0x42, 0xb2, 0x78, 0x32, 0xb3, 0xa2, 0x07, 0x60, 0xf3, 0xf4,
	0x4a, 0x90, 0x92, 0xf6, 0xe0, 0xe5, 0x1c, 0x49, 0x73, 0x34, 0xa0, 0x41, 0x36, 0x00, 0xa7, 0x90,
	0xa1, 0x2c, 0x0b, 0x52, 0xda, 0x1e, 0x74, 0xe7, 0x8e, 0xd0, 0x15, 0x97, 0x34, 0x11, 0xe8, 0x49,
	0xff, 0xb7, 0x31, 0x77, 0xf5, 0x27, 0x5e, 0xc8, 0x06, 0x93, 0xb1, 0x2e, 0x13, 0x2d, 0x87, 0x90,
	0x61, 0xac, 0x7f, 0x42, 0x15, 0x50, 0xeb, 0x95, 0x85, 0xd7, 0x78, 0x1a, 0xde, 0x51, 0x4c, 0x9d,
	0xa0, 0x86, 0x75, 0xe7, 0x4c, 0x8c, 0xe9, 0x29, 0x75, 0xe7, 0x4c, 0x8c, 0x95, 0xf1, 0x98, 0x17,
	0x52, 0xa7, 0xf7, 0xb8, 0x71, 0x35, 0x38, 0xf8, 0x6b, 0xc3, 0x93, 0xba, 0x7c, 0x89, 0xf9, 0x2d,
	0x1f, 0x21, 0xfb, 0x08, 0xce, 0x61, 0x14, 0x9d, 0xa7, 0xc8, 0xf6, 0x1f, 0x88, 0x6f, 0x6e, 0x65,
	0xd7, 0x5b, 0xe4, 0xad, 0x79, 0x89, 0xbf, 0xc1, 0x2e, 0xa0, 0x55, 0x6d, 0x87, 0xe2, 0xf3, 0x96,
	0xf3, 0x55, 0x43, 0x6b, 0x51, 0xbe, 0x07, 0x67, 0x88, 0x52, 0xf1, 0x3d, 0x0c, 0xf7, 0xa6, 0xc4,
	0x42, 0xaa, 0xb9, 0xb5, 0x98, 0x4e, 0x60, 0x6b, 0x88, 0x92, 0xde, 0x6d, 0x09, 0xd5, 0xe7, 0xf0,
	0x7a, 0x85, 0x28, 0x75, 0xda, 0xdf, 0x60, 0xc7, 0xd0, 0x0a, 0x30, 0x11, 0xb7, 0xb8, 0x4a, 0x97,
	0xbb, 0x88, 0x4c, 0xeb, 0x39, 0x87, 0xf6, 0x10, 0xe5, 0xd1, 0xe4, 0x1d, 0x8f, 0x25, 0xe6, 0xec,
	0xd5, 0x62, 0x9a, 0xaa, 0xbb, 0x96, 0xaa, 0x53, 0xd8, 0x19, 0xa2, 0x54, 0xeb, 0xc6, 0x0b, 0xc9,
	0x47, 0x2b, 0x18, 0xf7, 0x97, 0xed, 0x2a, 0x1d, 0xf6, 0x37, 0xd8, 0x07, 0xd8, 0xad, 0xde, 0x69,
	0x95, 0x44, 0xfd, 0x9a, 0x8f, 0x78, 0x3d, 0xea, 0x7c, 0x6d, 0x37, 0xfe, 0x73, 0xbe, 0x39, 0x04,
	0xde, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x3b, 0x26, 0xac, 0xb4, 0x06, 0x00, 0x00,
}
