// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/third/common.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PairInfo struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Count                uint64   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairInfo) Reset()         { *m = PairInfo{} }
func (m *PairInfo) String() string { return proto.CompactTextString(m) }
func (*PairInfo) ProtoMessage()    {}
func (*PairInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{0}
}

func (m *PairInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairInfo.Unmarshal(m, b)
}
func (m *PairInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairInfo.Marshal(b, m, deterministic)
}
func (m *PairInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairInfo.Merge(m, src)
}
func (m *PairInfo) XXX_Size() int {
	return xxx_messageInfo_PairInfo.Size(m)
}
func (m *PairInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PairInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PairInfo proto.InternalMessageInfo

func (m *PairInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PairInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PairInfo) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PairInfo) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RequestInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{1}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type RequestIDInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestIDInfo) Reset()         { *m = RequestIDInfo{} }
func (m *RequestIDInfo) String() string { return proto.CompactTextString(m) }
func (*RequestIDInfo) ProtoMessage()    {}
func (*RequestIDInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{2}
}

func (m *RequestIDInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestIDInfo.Unmarshal(m, b)
}
func (m *RequestIDInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestIDInfo.Marshal(b, m, deterministic)
}
func (m *RequestIDInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestIDInfo.Merge(m, src)
}
func (m *RequestIDInfo) XXX_Size() int {
	return xxx_messageInfo_RequestIDInfo.Size(m)
}
func (m *RequestIDInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestIDInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestIDInfo proto.InternalMessageInfo

func (m *RequestIDInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestIDInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type RequestPage struct {
	Number               uint32   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPage) Reset()         { *m = RequestPage{} }
func (m *RequestPage) String() string { return proto.CompactTextString(m) }
func (*RequestPage) ProtoMessage()    {}
func (*RequestPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{3}
}

func (m *RequestPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPage.Unmarshal(m, b)
}
func (m *RequestPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPage.Marshal(b, m, deterministic)
}
func (m *RequestPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPage.Merge(m, src)
}
func (m *RequestPage) XXX_Size() int {
	return xxx_messageInfo_RequestPage.Size(m)
}
func (m *RequestPage) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPage.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPage proto.InternalMessageInfo

func (m *RequestPage) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RequestPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RequestPage) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type RequestFilter struct {
	Scene                string   `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Page                 uint32   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32   `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []string `protobuf:"bytes,7,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFilter) Reset()         { *m = RequestFilter{} }
func (m *RequestFilter) String() string { return proto.CompactTextString(m) }
func (*RequestFilter) ProtoMessage()    {}
func (*RequestFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{4}
}

func (m *RequestFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFilter.Unmarshal(m, b)
}
func (m *RequestFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFilter.Marshal(b, m, deterministic)
}
func (m *RequestFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFilter.Merge(m, src)
}
func (m *RequestFilter) XXX_Size() int {
	return xxx_messageInfo_RequestFilter.Size(m)
}
func (m *RequestFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFilter.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFilter proto.InternalMessageInfo

func (m *RequestFilter) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *RequestFilter) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *RequestFilter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RequestFilter) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RequestFilter) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RequestFilter) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type RequestUpdate struct {
	Scene                string   `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Field                string   `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	List                 []string `protobuf:"bytes,20,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestUpdate) Reset()         { *m = RequestUpdate{} }
func (m *RequestUpdate) String() string { return proto.CompactTextString(m) }
func (*RequestUpdate) ProtoMessage()    {}
func (*RequestUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{5}
}

func (m *RequestUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestUpdate.Unmarshal(m, b)
}
func (m *RequestUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestUpdate.Marshal(b, m, deterministic)
}
func (m *RequestUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestUpdate.Merge(m, src)
}
func (m *RequestUpdate) XXX_Size() int {
	return xxx_messageInfo_RequestUpdate.Size(m)
}
func (m *RequestUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_RequestUpdate proto.InternalMessageInfo

func (m *RequestUpdate) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *RequestUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestUpdate) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *RequestUpdate) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RequestUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestUpdate) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyStatus struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyStatus) Reset()         { *m = ReplyStatus{} }
func (m *ReplyStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyStatus) ProtoMessage()    {}
func (*ReplyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{6}
}

func (m *ReplyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatus.Unmarshal(m, b)
}
func (m *ReplyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatus.Marshal(b, m, deterministic)
}
func (m *ReplyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatus.Merge(m, src)
}
func (m *ReplyStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyStatus.Size(m)
}
func (m *ReplyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatus proto.InternalMessageInfo

func (m *ReplyStatus) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReplyStatus) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ReplyInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Uid                  string       `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{7}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type ReplyStatistic struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Key                  string       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Owner                string       `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Count                uint64       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	List                 []*PairInfo  `protobuf:"bytes,10,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStatistic) Reset()         { *m = ReplyStatistic{} }
func (m *ReplyStatistic) String() string { return proto.CompactTextString(m) }
func (*ReplyStatistic) ProtoMessage()    {}
func (*ReplyStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{8}
}

func (m *ReplyStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatistic.Unmarshal(m, b)
}
func (m *ReplyStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatistic.Marshal(b, m, deterministic)
}
func (m *ReplyStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatistic.Merge(m, src)
}
func (m *ReplyStatistic) XXX_Size() int {
	return xxx_messageInfo_ReplyStatistic.Size(m)
}
func (m *ReplyStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatistic proto.InternalMessageInfo

func (m *ReplyStatistic) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyStatistic) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReplyStatistic) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReplyStatistic) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReplyStatistic) GetList() []*PairInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*PairInfo)(nil), "omo.msp.third.PairInfo")
	proto.RegisterType((*RequestInfo)(nil), "omo.msp.third.RequestInfo")
	proto.RegisterType((*RequestIDInfo)(nil), "omo.msp.third.RequestIDInfo")
	proto.RegisterType((*RequestPage)(nil), "omo.msp.third.RequestPage")
	proto.RegisterType((*RequestFilter)(nil), "omo.msp.third.RequestFilter")
	proto.RegisterType((*RequestUpdate)(nil), "omo.msp.third.RequestUpdate")
	proto.RegisterType((*ReplyStatus)(nil), "omo.msp.third.ReplyStatus")
	proto.RegisterType((*ReplyInfo)(nil), "omo.msp.third.ReplyInfo")
	proto.RegisterType((*ReplyStatistic)(nil), "omo.msp.third.ReplyStatistic")
}

func init() {
	proto.RegisterFile("proto/third/common.proto", fileDescriptor_fdcd80a2ad56f384)
}

var fileDescriptor_fdcd80a2ad56f384 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcd, 0x8a, 0xd4, 0x40,
	0x10, 0xc7, 0xc9, 0xc7, 0x8c, 0x9b, 0x0e, 0x59, 0xa4, 0x59, 0x34, 0xec, 0x29, 0xe4, 0x14, 0x10,
	0xb2, 0x30, 0x7b, 0xf4, 0x26, 0x22, 0x78, 0x72, 0x6d, 0x11, 0xc4, 0x5b, 0x36, 0x5d, 0x1b, 0x1b,
	0x93, 0x74, 0xec, 0xee, 0x28, 0xf3, 0x18, 0xe2, 0x83, 0xf8, 0x8a, 0xd2, 0x95, 0xaf, 0xde, 0xdd,
	0xd1, 0x83, 0xb7, 0xfa, 0x57, 0xea, 0xe3, 0xd7, 0x55, 0x29, 0x92, 0x0e, 0x4a, 0x1a, 0x79, 0x65,
	0xbe, 0x08, 0xc5, 0xaf, 0x6a, 0xd9, 0x75, 0xb2, 0x2f, 0xd1, 0x45, 0x13, 0xd9, 0xc9, 0xb2, 0xd3,
	0x43, 0x89, 0xdf, 0xf2, 0x4f, 0xe4, 0xec, 0xa6, 0x12, 0xea, 0x6d, 0x7f, 0x27, 0xe9, 0x53, 0x12,
	0x7c, 0x85, 0x63, 0xea, 0x65, 0x5e, 0x11, 0x31, 0x6b, 0xd2, 0x73, 0xe2, 0x0b, 0x9e, 0xfa, 0x99,
	0x57, 0x84, 0xcc, 0x17, 0x9c, 0x5e, 0x90, 0x5d, 0x2d, 0xc7, 0xde, 0xa4, 0x01, 0xba, 0x26, 0x61,
	0xbd, 0xdf, 0xab, 0x76, 0x84, 0x34, 0xc4, 0xcc, 0x49, 0xe4, 0xef, 0x48, 0xcc, 0xe0, 0xdb, 0x08,
	0xda, 0x2c, 0xc5, 0x47, 0xc1, 0x97, 0xe2, 0xa3, 0xe0, 0xf4, 0x92, 0x9c, 0xc9, 0x01, 0x54, 0x65,
	0xa4, 0xc2, 0x16, 0x11, 0x5b, 0x35, 0xa5, 0x24, 0x34, 0xc7, 0x01, 0xb0, 0x4f, 0xc2, 0xd0, 0xce,
	0x5f, 0x92, 0x64, 0x29, 0xf8, 0x1a, 0x4b, 0x4e, 0x74, 0xde, 0x4a, 0xf7, 0x8f, 0x82, 0x0e, 0xcd,
	0x4d, 0xd5, 0x00, 0x7d, 0x46, 0xf6, 0xfd, 0xd8, 0xdd, 0x82, 0xc2, 0xf4, 0x84, 0xcd, 0xca, 0xf6,
	0x1d, 0xaa, 0x06, 0x30, 0x3d, 0x61, 0x68, 0xdb, 0xe7, 0xc9, 0x1f, 0x3d, 0x28, 0x84, 0x89, 0xd8,
	0x24, 0xf2, 0x9f, 0xde, 0x8a, 0xf3, 0x46, 0xb4, 0x06, 0x94, 0x8d, 0xd3, 0x35, 0xf4, 0x30, 0xbf,
	0x71, 0x12, 0xd6, 0x7b, 0x27, 0xa0, 0xe5, 0x33, 0xd1, 0x24, 0xb6, 0x91, 0x05, 0xce, 0xc8, 0xd6,
	0xee, 0xa1, 0xd3, 0x7d, 0x23, 0xdd, 0x3d, 0x24, 0x6d, 0x85, 0x36, 0xe9, 0x93, 0x2c, 0x28, 0x22,
	0x86, 0x76, 0xfe, 0x6b, 0x63, 0xfa, 0x38, 0xf0, 0xca, 0xc0, 0x5f, 0x98, 0xe6, 0x5d, 0xf8, 0xdb,
	0x2e, 0x56, 0xca, 0xe0, 0x24, 0xa5, 0xbb, 0xd8, 0x7b, 0x63, 0xde, 0x3d, 0xde, 0x1b, 0x52, 0x5d,
	0x38, 0x54, 0xd7, 0x76, 0xf4, 0x43, 0x7b, 0xfc, 0x60, 0x2a, 0x33, 0x6a, 0x1b, 0x52, 0x4b, 0x0e,
	0xf3, 0xe0, 0xd1, 0xb6, 0x40, 0x9d, 0x6e, 0x16, 0xa0, 0x4e, 0x37, 0xf9, 0x7b, 0x12, 0x61, 0x12,
	0x2e, 0xfa, 0x40, 0xf6, 0x1a, 0x93, 0x31, 0x29, 0x3e, 0x5c, 0x96, 0xf7, 0x7e, 0xe2, 0xd2, 0x29,
	0xcf, 0xe6, 0xc8, 0xc7, 0x6f, 0xcc, 0x7f, 0x7b, 0xe4, 0x7c, 0x8d, 0x14, 0xda, 0x88, 0xfa, 0x7f,
	0x0b, 0xdb, 0x2b, 0xf1, 0xb7, 0x2b, 0x39, 0xf9, 0x83, 0x6c, 0xb7, 0x12, 0xba, 0xb7, 0xf2, 0x62,
	0x1e, 0x10, 0xc9, 0x82, 0x22, 0x3e, 0x3c, 0x7f, 0xd0, 0x6f, 0x39, 0xc5, 0x69, 0x72, 0xaf, 0x92,
	0xcf, 0xb1, 0x73, 0xc7, 0xb7, 0x7b, 0x14, 0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x62, 0xe9,
	0xe7, 0x21, 0xdd, 0x03, 0x00, 0x00,
}
