// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/third/common.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultCode int32

const (
	ResultCode_Success     ResultCode = 0
	ResultCode_MaxLimit    ResultCode = 1
	ResultCode_Repeated    ResultCode = 2
	ResultCode_NotExisted  ResultCode = 3
	ResultCode_DBException ResultCode = 4
	ResultCode_Empty       ResultCode = 5
)

var ResultCode_name = map[int32]string{
	0: "Success",
	1: "MaxLimit",
	2: "Repeated",
	3: "NotExisted",
	4: "DBException",
	5: "Empty",
}

var ResultCode_value = map[string]int32{
	"Success":     0,
	"MaxLimit":    1,
	"Repeated":    2,
	"NotExisted":  3,
	"DBException": 4,
	"Empty":       5,
}

func (x ResultCode) String() string {
	return proto.EnumName(ResultCode_name, int32(x))
}

func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{0}
}

type RequestInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Entity               string   `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{0}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestInfo) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *RequestInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type RequestIDInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestIDInfo) Reset()         { *m = RequestIDInfo{} }
func (m *RequestIDInfo) String() string { return proto.CompactTextString(m) }
func (*RequestIDInfo) ProtoMessage()    {}
func (*RequestIDInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{1}
}

func (m *RequestIDInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestIDInfo.Unmarshal(m, b)
}
func (m *RequestIDInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestIDInfo.Marshal(b, m, deterministic)
}
func (m *RequestIDInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestIDInfo.Merge(m, src)
}
func (m *RequestIDInfo) XXX_Size() int {
	return xxx_messageInfo_RequestIDInfo.Size(m)
}
func (m *RequestIDInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestIDInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestIDInfo proto.InternalMessageInfo

func (m *RequestIDInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestIDInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type RequestPage struct {
	Number               uint32   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPage) Reset()         { *m = RequestPage{} }
func (m *RequestPage) String() string { return proto.CompactTextString(m) }
func (*RequestPage) ProtoMessage()    {}
func (*RequestPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{2}
}

func (m *RequestPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPage.Unmarshal(m, b)
}
func (m *RequestPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPage.Marshal(b, m, deterministic)
}
func (m *RequestPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPage.Merge(m, src)
}
func (m *RequestPage) XXX_Size() int {
	return xxx_messageInfo_RequestPage.Size(m)
}
func (m *RequestPage) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPage.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPage proto.InternalMessageInfo

func (m *RequestPage) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RequestPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ReplyStatus struct {
	Code                 ResultCode `protobuf:"varint,1,opt,name=code,proto3,enum=omo.msp.third.ResultCode" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReplyStatus) Reset()         { *m = ReplyStatus{} }
func (m *ReplyStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyStatus) ProtoMessage()    {}
func (*ReplyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{3}
}

func (m *ReplyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatus.Unmarshal(m, b)
}
func (m *ReplyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatus.Marshal(b, m, deterministic)
}
func (m *ReplyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatus.Merge(m, src)
}
func (m *ReplyStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyStatus.Size(m)
}
func (m *ReplyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatus proto.InternalMessageInfo

func (m *ReplyStatus) GetCode() ResultCode {
	if m != nil {
		return m.Code
	}
	return ResultCode_Success
}

func (m *ReplyStatus) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ReplyInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Uid                  string       `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdcd80a2ad56f384, []int{4}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterEnum("omo.msp.third.ResultCode", ResultCode_name, ResultCode_value)
	proto.RegisterType((*RequestInfo)(nil), "omo.msp.third.RequestInfo")
	proto.RegisterType((*RequestIDInfo)(nil), "omo.msp.third.RequestIDInfo")
	proto.RegisterType((*RequestPage)(nil), "omo.msp.third.RequestPage")
	proto.RegisterType((*ReplyStatus)(nil), "omo.msp.third.ReplyStatus")
	proto.RegisterType((*ReplyInfo)(nil), "omo.msp.third.ReplyInfo")
}

func init() {
	proto.RegisterFile("proto/third/common.proto", fileDescriptor_fdcd80a2ad56f384)
}

var fileDescriptor_fdcd80a2ad56f384 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0xa5, 0x14, 0x84, 0xa9, 0xc5, 0x66, 0x0f, 0xa6, 0x72, 0x32, 0x3d, 0x19, 0x13, 0x4b,
	0x82, 0x27, 0xe3, 0x0d, 0xe1, 0x60, 0xa2, 0x44, 0x97, 0x9b, 0xb7, 0xd2, 0x8e, 0xb8, 0x09, 0xdb,
	0x5d, 0xbb, 0xdb, 0x04, 0xbe, 0xbd, 0xd9, 0x49, 0xa9, 0xa2, 0xb7, 0x79, 0x3b, 0xf3, 0x7e, 0xf3,
	0x67, 0x21, 0xd6, 0x95, 0xb2, 0x6a, 0x62, 0x3f, 0x45, 0x55, 0x4c, 0x72, 0x25, 0xa5, 0x2a, 0x53,
	0x7a, 0x62, 0xa1, 0x92, 0x2a, 0x95, 0x46, 0xa7, 0x94, 0x4b, 0x56, 0x10, 0x70, 0xfc, 0xaa, 0xd1,
	0xd8, 0xa7, 0xf2, 0x43, 0xb1, 0x08, 0xba, 0xb5, 0x28, 0xe2, 0xce, 0x55, 0xe7, 0x7a, 0xc8, 0x5d,
	0xc8, 0x2e, 0xa0, 0x8f, 0xa5, 0x15, 0x76, 0x1f, 0x7b, 0xf4, 0xd8, 0x28, 0x36, 0x86, 0x81, 0xd2,
	0x58, 0x65, 0x56, 0x55, 0x71, 0x97, 0x32, 0xad, 0x4e, 0x1e, 0x20, 0x3c, 0x40, 0xe7, 0x84, 0x1d,
	0x81, 0xd7, 0x50, 0x7d, 0xee, 0x89, 0xe2, 0xc8, 0xec, 0xfd, 0x31, 0xdf, 0xb7, 0x13, 0xbd, 0x66,
	0x1b, 0x74, 0xfd, 0xcb, 0x5a, 0xae, 0xb1, 0x22, 0x7b, 0xc8, 0x1b, 0xc5, 0x18, 0xf8, 0x3a, 0xdb,
	0x20, 0xd9, 0x43, 0x4e, 0x71, 0xb2, 0x74, 0x56, 0xbd, 0xdd, 0xaf, 0x6c, 0x66, 0x6b, 0xc3, 0x6e,
	0xc1, 0xcf, 0x55, 0x81, 0x64, 0x1c, 0x4d, 0x2f, 0xd3, 0xa3, 0xcd, 0x53, 0x8e, 0xa6, 0xde, 0xda,
	0x47, 0x55, 0x20, 0xa7, 0x32, 0xb7, 0xbb, 0x34, 0x9b, 0x66, 0x1e, 0x17, 0x26, 0x6f, 0x30, 0x24,
	0x1e, 0xed, 0x30, 0x85, 0xbe, 0x21, 0x2e, 0xf1, 0x82, 0xe9, 0xf8, 0x1f, 0xaf, 0xed, 0xcc, 0x9b,
	0xca, 0xc3, 0x39, 0xbd, 0xf6, 0x9c, 0x37, 0x19, 0xc0, 0x4f, 0x63, 0x16, 0xc0, 0xe9, 0xaa, 0xce,
	0x73, 0x34, 0x26, 0x3a, 0x61, 0x67, 0x30, 0x78, 0xc9, 0x76, 0xcf, 0x42, 0x0a, 0x1b, 0x75, 0x9c,
	0xe2, 0xa8, 0x31, 0xb3, 0x58, 0x44, 0x1e, 0x1b, 0x01, 0x2c, 0x95, 0x5d, 0xec, 0x84, 0x71, 0xba,
	0xcb, 0xce, 0x21, 0x98, 0xcf, 0x16, 0xbb, 0x1c, 0xb5, 0x15, 0xaa, 0x8c, 0x7c, 0x36, 0x84, 0xde,
	0x42, 0x6a, 0xbb, 0x8f, 0x7a, 0xb3, 0xf0, 0x3d, 0xf8, 0xf5, 0xfb, 0xeb, 0x3e, 0x89, 0xbb, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x46, 0x04, 0x35, 0x13, 0x02, 0x00, 0x00,
}
