// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/third/kms.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KMSInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Sn                   string   `protobuf:"bytes,10,opt,name=sn,proto3" json:"sn,omitempty"`
	Consumer             string   `protobuf:"bytes,11,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Space                string   `protobuf:"bytes,12,opt,name=space,proto3" json:"space,omitempty"`
	Scene                string   `protobuf:"bytes,13,opt,name=scene,proto3" json:"scene,omitempty"`
	Owner                string   `protobuf:"bytes,14,opt,name=owner,proto3" json:"owner,omitempty"`
	Content              string   `protobuf:"bytes,15,opt,name=content,proto3" json:"content,omitempty"`
	Expiry               uint32   `protobuf:"varint,16,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KMSInfo) Reset()         { *m = KMSInfo{} }
func (m *KMSInfo) String() string { return proto.CompactTextString(m) }
func (*KMSInfo) ProtoMessage()    {}
func (*KMSInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_93cb5bc0908cf076, []int{0}
}

func (m *KMSInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KMSInfo.Unmarshal(m, b)
}
func (m *KMSInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KMSInfo.Marshal(b, m, deterministic)
}
func (m *KMSInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KMSInfo.Merge(m, src)
}
func (m *KMSInfo) XXX_Size() int {
	return xxx_messageInfo_KMSInfo.Size(m)
}
func (m *KMSInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KMSInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KMSInfo proto.InternalMessageInfo

func (m *KMSInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *KMSInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KMSInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *KMSInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *KMSInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *KMSInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *KMSInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KMSInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *KMSInfo) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *KMSInfo) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *KMSInfo) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

func (m *KMSInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *KMSInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *KMSInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *KMSInfo) GetExpiry() uint32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type ReqKMSAdd struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Sn                   string   `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	Consumer             string   `protobuf:"bytes,3,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Scene                string   `protobuf:"bytes,4,opt,name=scene,proto3" json:"scene,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Expiry               uint32   `protobuf:"varint,6,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Content              string   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Space                string   `protobuf:"bytes,9,opt,name=space,proto3" json:"space,omitempty"`
	Name                 string   `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqKMSAdd) Reset()         { *m = ReqKMSAdd{} }
func (m *ReqKMSAdd) String() string { return proto.CompactTextString(m) }
func (*ReqKMSAdd) ProtoMessage()    {}
func (*ReqKMSAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_93cb5bc0908cf076, []int{1}
}

func (m *ReqKMSAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqKMSAdd.Unmarshal(m, b)
}
func (m *ReqKMSAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqKMSAdd.Marshal(b, m, deterministic)
}
func (m *ReqKMSAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqKMSAdd.Merge(m, src)
}
func (m *ReqKMSAdd) XXX_Size() int {
	return xxx_messageInfo_ReqKMSAdd.Size(m)
}
func (m *ReqKMSAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqKMSAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqKMSAdd proto.InternalMessageInfo

func (m *ReqKMSAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqKMSAdd) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *ReqKMSAdd) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *ReqKMSAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqKMSAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqKMSAdd) GetExpiry() uint32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *ReqKMSAdd) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReqKMSAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqKMSAdd) GetSpace() string {
	if m != nil {
		return m.Space
	}
	return ""
}

func (m *ReqKMSAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReplyKMSInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *KMSInfo     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyKMSInfo) Reset()         { *m = ReplyKMSInfo{} }
func (m *ReplyKMSInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyKMSInfo) ProtoMessage()    {}
func (*ReplyKMSInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_93cb5bc0908cf076, []int{2}
}

func (m *ReplyKMSInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyKMSInfo.Unmarshal(m, b)
}
func (m *ReplyKMSInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyKMSInfo.Marshal(b, m, deterministic)
}
func (m *ReplyKMSInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyKMSInfo.Merge(m, src)
}
func (m *ReplyKMSInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyKMSInfo.Size(m)
}
func (m *ReplyKMSInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyKMSInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyKMSInfo proto.InternalMessageInfo

func (m *ReplyKMSInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyKMSInfo) GetInfo() *KMSInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyKMSList struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32       `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32       `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32       `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*KMSInfo   `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyKMSList) Reset()         { *m = ReplyKMSList{} }
func (m *ReplyKMSList) String() string { return proto.CompactTextString(m) }
func (*ReplyKMSList) ProtoMessage()    {}
func (*ReplyKMSList) Descriptor() ([]byte, []int) {
	return fileDescriptor_93cb5bc0908cf076, []int{3}
}

func (m *ReplyKMSList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyKMSList.Unmarshal(m, b)
}
func (m *ReplyKMSList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyKMSList.Marshal(b, m, deterministic)
}
func (m *ReplyKMSList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyKMSList.Merge(m, src)
}
func (m *ReplyKMSList) XXX_Size() int {
	return xxx_messageInfo_ReplyKMSList.Size(m)
}
func (m *ReplyKMSList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyKMSList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyKMSList proto.InternalMessageInfo

func (m *ReplyKMSList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyKMSList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyKMSList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyKMSList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyKMSList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyKMSList) GetList() []*KMSInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*KMSInfo)(nil), "omo.msp.third.KMSInfo")
	proto.RegisterType((*ReqKMSAdd)(nil), "omo.msp.third.ReqKMSAdd")
	proto.RegisterType((*ReplyKMSInfo)(nil), "omo.msp.third.ReplyKMSInfo")
	proto.RegisterType((*ReplyKMSList)(nil), "omo.msp.third.ReplyKMSList")
}

func init() {
	proto.RegisterFile("proto/third/kms.proto", fileDescriptor_93cb5bc0908cf076)
}

var fileDescriptor_93cb5bc0908cf076 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x25, 0x01, 0x02, 0x18, 0xd2, 0x21, 0xab, 0xab, 0x2c, 0xb6, 0x49, 0x28, 0x4f, 0x68, 0x0f,
	0x54, 0x62, 0x5f, 0x40, 0x27, 0x0d, 0x6d, 0x0c, 0x4d, 0x32, 0x6f, 0x7b, 0x4b, 0x93, 0xdb, 0xcd,
	0x2a, 0xb1, 0x53, 0xdb, 0xd9, 0xc6, 0x57, 0xed, 0x2f, 0xf6, 0x1f, 0xfb, 0x86, 0xfd, 0xc0, 0xe4,
	0x9b, 0x00, 0x69, 0xa1, 0xab, 0xb4, 0x37, 0x9f, 0x7b, 0x4f, 0x8e, 0xef, 0x39, 0xd7, 0x0a, 0x79,
	0x9e, 0x6b, 0x65, 0xd5, 0xa5, 0xfd, 0x2a, 0x74, 0x7a, 0x79, 0x9b, 0x99, 0x29, 0x62, 0x1a, 0xaa,
	0x4c, 0x4d, 0x33, 0x93, 0x4f, 0xb1, 0x31, 0x62, 0x75, 0x56, 0xa2, 0xb2, 0x4c, 0xc9, 0x92, 0x18,
	0xfd, 0xf6, 0x49, 0x67, 0xb9, 0x5a, 0xbf, 0x97, 0x37, 0x8a, 0x0e, 0x49, 0xb3, 0x10, 0x29, 0xf3,
	0xc6, 0xde, 0xa4, 0xc7, 0xdd, 0x91, 0x9e, 0x11, 0x5f, 0xa4, 0xcc, 0x1f, 0x7b, 0x93, 0x16, 0xf7,
	0x45, 0x4a, 0x19, 0xe9, 0x24, 0x1a, 0x62, 0x0b, 0x29, 0x6b, 0x8d, 0xbd, 0x49, 0x93, 0xef, 0xa0,
	0xeb, 0x14, 0x79, 0x8a, 0x9d, 0x76, 0xd9, 0xa9, 0xe0, 0xfe, 0x1b, 0xa5, 0x59, 0x80, 0xca, 0x3b,
	0x48, 0x47, 0xa4, 0xab, 0x72, 0xd0, 0xd8, 0xea, 0x60, 0x6b, 0x8f, 0x29, 0x25, 0x2d, 0x19, 0x67,
	0xc0, 0xba, 0x58, 0xc7, 0x33, 0xbd, 0x20, 0x81, 0x86, 0x2c, 0xd6, 0xb7, 0xac, 0x87, 0xd5, 0x0a,
	0xb9, 0x29, 0x8d, 0x64, 0x04, 0x6b, 0xbe, 0x91, 0x4e, 0x37, 0x51, 0xd2, 0x14, 0x19, 0x68, 0xd6,
	0x2f, 0x75, 0x77, 0x98, 0x9e, 0x93, 0xb6, 0xc9, 0xe3, 0x04, 0xd8, 0x00, 0x1b, 0x25, 0xc0, 0x6a,
	0x02, 0x12, 0x58, 0x58, 0x55, 0x1d, 0x70, 0x55, 0xf5, 0x5d, 0x82, 0x66, 0x67, 0x65, 0x15, 0x01,
	0xfa, 0x51, 0xd2, 0x82, 0xb4, 0xec, 0x59, 0xe5, 0xa7, 0x84, 0x6e, 0x3e, 0xf8, 0x91, 0x0b, 0xbd,
	0x65, 0xc3, 0xb1, 0x37, 0x09, 0x79, 0x85, 0xa2, 0x3f, 0x1e, 0xe9, 0x71, 0xb8, 0x5b, 0xae, 0xd6,
	0xf3, 0x34, 0x3d, 0xa8, 0x7a, 0x75, 0xd5, 0xd2, 0x83, 0x7f, 0xd2, 0x43, 0xf3, 0x84, 0x07, 0x9c,
	0xb6, 0x55, 0x9f, 0xb6, 0x9e, 0x66, 0xfb, 0x41, 0x9a, 0x87, 0xc9, 0x82, 0xfa, 0x64, 0x75, 0x2f,
	0x9d, 0x23, 0x2f, 0x55, 0xd6, 0xdd, 0x7b, 0x59, 0xef, 0xf3, 0xeb, 0xd5, 0xf3, 0xdb, 0x6d, 0x8b,
	0x1c, 0xb6, 0x15, 0x49, 0x32, 0xe0, 0x90, 0x6f, 0xb6, 0xbb, 0xd7, 0x35, 0x23, 0x81, 0xb1, 0xb1,
	0x2d, 0x0c, 0x1a, 0xef, 0xcf, 0x46, 0xd3, 0x7b, 0x6f, 0x74, 0x8a, 0xe4, 0x35, 0x32, 0x78, 0xc5,
	0xa4, 0xaf, 0x49, 0x4b, 0xc8, 0x1b, 0x85, 0xb9, 0xf4, 0x67, 0x17, 0x0f, 0xbe, 0xa8, 0x94, 0x39,
	0x72, 0xa2, 0x5f, 0xde, 0xe1, 0xc2, 0x8f, 0xc2, 0xd8, 0xff, 0xba, 0xf0, 0x9c, 0xb4, 0xad, 0xb2,
	0xf1, 0x06, 0x6f, 0x0c, 0x79, 0x09, 0x5c, 0x35, 0x8f, 0xbf, 0x80, 0xc1, 0x4d, 0x84, 0xbc, 0x04,
	0xce, 0xb4, 0x3b, 0xe0, 0x16, 0x42, 0x8e, 0x67, 0x17, 0x9b, 0x2c, 0xb2, 0x6b, 0x28, 0x57, 0x10,
	0xf2, 0x0a, 0x39, 0x23, 0x1b, 0x61, 0x2c, 0x1b, 0x8e, 0x9b, 0xff, 0x32, 0xe2, 0x38, 0xb3, 0x9f,
	0x3e, 0x21, 0xcb, 0xd5, 0x7a, 0x0d, 0xfa, 0x9b, 0x48, 0x80, 0xce, 0x49, 0x30, 0x4f, 0xd3, 0x4f,
	0x12, 0x28, 0x3b, 0x32, 0x50, 0xbd, 0xa9, 0xd1, 0x8b, 0x53, 0xd6, 0x2a, 0xd5, 0xa8, 0x41, 0xdf,
	0x92, 0x60, 0x01, 0xd6, 0x49, 0x1c, 0x67, 0x70, 0x57, 0x80, 0xb1, 0x8e, 0xf7, 0x94, 0xc8, 0x07,
	0xd2, 0x5f, 0x80, 0xbd, 0xda, 0xbe, 0x13, 0x1b, 0x0b, 0x9a, 0xbe, 0x3c, 0xad, 0x54, 0x76, 0x1f,
	0xd5, 0x72, 0x8b, 0x89, 0x1a, 0x74, 0x45, 0x06, 0x0b, 0xb0, 0x2e, 0x7b, 0x61, 0xac, 0x48, 0x9e,
	0x10, 0x7b, 0xf5, 0xd8, 0xe2, 0xf0, 0xe3, 0xa8, 0x71, 0x15, 0x7e, 0xee, 0xd7, 0x7e, 0x70, 0xd7,
	0x01, 0x82, 0x37, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x48, 0x6c, 0xd1, 0x1c, 0x05, 0x00,
	0x00,
}
