// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/third/netflow.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetflowInfo struct {
	Uid                  string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64         `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 uint32         `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Created              int64          `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Creator              string         `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Name                 string         `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Quote                string         `protobuf:"bytes,7,opt,name=quote,proto3" json:"quote,omitempty"`
	Scene                string         `protobuf:"bytes,8,opt,name=scene,proto3" json:"scene,omitempty"`
	Size                 uint32         `protobuf:"varint,9,opt,name=size,proto3" json:"size,omitempty"`
	Template             string         `protobuf:"bytes,10,opt,name=template,proto3" json:"template,omitempty"`
	Target               string         `protobuf:"bytes,11,opt,name=target,proto3" json:"target,omitempty"`
	Contents             []*ContentInfo `protobuf:"bytes,21,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NetflowInfo) Reset()         { *m = NetflowInfo{} }
func (m *NetflowInfo) String() string { return proto.CompactTextString(m) }
func (*NetflowInfo) ProtoMessage()    {}
func (*NetflowInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb66cca61b7c6432, []int{0}
}

func (m *NetflowInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetflowInfo.Unmarshal(m, b)
}
func (m *NetflowInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetflowInfo.Marshal(b, m, deterministic)
}
func (m *NetflowInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetflowInfo.Merge(m, src)
}
func (m *NetflowInfo) XXX_Size() int {
	return xxx_messageInfo_NetflowInfo.Size(m)
}
func (m *NetflowInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetflowInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetflowInfo proto.InternalMessageInfo

func (m *NetflowInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *NetflowInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NetflowInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NetflowInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *NetflowInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *NetflowInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetflowInfo) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *NetflowInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *NetflowInfo) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *NetflowInfo) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *NetflowInfo) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *NetflowInfo) GetContents() []*ContentInfo {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ContentInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Group                string   `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentInfo) Reset()         { *m = ContentInfo{} }
func (m *ContentInfo) String() string { return proto.CompactTextString(m) }
func (*ContentInfo) ProtoMessage()    {}
func (*ContentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb66cca61b7c6432, []int{1}
}

func (m *ContentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentInfo.Unmarshal(m, b)
}
func (m *ContentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentInfo.Marshal(b, m, deterministic)
}
func (m *ContentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentInfo.Merge(m, src)
}
func (m *ContentInfo) XXX_Size() int {
	return xxx_messageInfo_ContentInfo.Size(m)
}
func (m *ContentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContentInfo proto.InternalMessageInfo

func (m *ContentInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ContentInfo) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ContentInfo) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *ContentInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReqNetflowAdd struct {
	Type                 uint32         `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Scene                string         `protobuf:"bytes,4,opt,name=scene,proto3" json:"scene,omitempty"`
	Operator             string         `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Quote                string         `protobuf:"bytes,6,opt,name=quote,proto3" json:"quote,omitempty"`
	Template             string         `protobuf:"bytes,7,opt,name=template,proto3" json:"template,omitempty"`
	Target               string         `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	Contents             []*ContentInfo `protobuf:"bytes,11,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReqNetflowAdd) Reset()         { *m = ReqNetflowAdd{} }
func (m *ReqNetflowAdd) String() string { return proto.CompactTextString(m) }
func (*ReqNetflowAdd) ProtoMessage()    {}
func (*ReqNetflowAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb66cca61b7c6432, []int{2}
}

func (m *ReqNetflowAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNetflowAdd.Unmarshal(m, b)
}
func (m *ReqNetflowAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNetflowAdd.Marshal(b, m, deterministic)
}
func (m *ReqNetflowAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNetflowAdd.Merge(m, src)
}
func (m *ReqNetflowAdd) XXX_Size() int {
	return xxx_messageInfo_ReqNetflowAdd.Size(m)
}
func (m *ReqNetflowAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNetflowAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNetflowAdd proto.InternalMessageInfo

func (m *ReqNetflowAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqNetflowAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqNetflowAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqNetflowAdd) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *ReqNetflowAdd) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *ReqNetflowAdd) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ReqNetflowAdd) GetContents() []*ContentInfo {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ReplyNetflowInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *NetflowInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyNetflowInfo) Reset()         { *m = ReplyNetflowInfo{} }
func (m *ReplyNetflowInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyNetflowInfo) ProtoMessage()    {}
func (*ReplyNetflowInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb66cca61b7c6432, []int{3}
}

func (m *ReplyNetflowInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyNetflowInfo.Unmarshal(m, b)
}
func (m *ReplyNetflowInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyNetflowInfo.Marshal(b, m, deterministic)
}
func (m *ReplyNetflowInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyNetflowInfo.Merge(m, src)
}
func (m *ReplyNetflowInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyNetflowInfo.Size(m)
}
func (m *ReplyNetflowInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyNetflowInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyNetflowInfo proto.InternalMessageInfo

func (m *ReplyNetflowInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyNetflowInfo) GetInfo() *NetflowInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyNetflowList struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32         `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32         `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32         `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*NetflowInfo `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyNetflowList) Reset()         { *m = ReplyNetflowList{} }
func (m *ReplyNetflowList) String() string { return proto.CompactTextString(m) }
func (*ReplyNetflowList) ProtoMessage()    {}
func (*ReplyNetflowList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb66cca61b7c6432, []int{4}
}

func (m *ReplyNetflowList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyNetflowList.Unmarshal(m, b)
}
func (m *ReplyNetflowList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyNetflowList.Marshal(b, m, deterministic)
}
func (m *ReplyNetflowList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyNetflowList.Merge(m, src)
}
func (m *ReplyNetflowList) XXX_Size() int {
	return xxx_messageInfo_ReplyNetflowList.Size(m)
}
func (m *ReplyNetflowList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyNetflowList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyNetflowList proto.InternalMessageInfo

func (m *ReplyNetflowList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyNetflowList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyNetflowList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyNetflowList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyNetflowList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyNetflowList) GetList() []*NetflowInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*NetflowInfo)(nil), "omo.msp.third.NetflowInfo")
	proto.RegisterType((*ContentInfo)(nil), "omo.msp.third.ContentInfo")
	proto.RegisterType((*ReqNetflowAdd)(nil), "omo.msp.third.ReqNetflowAdd")
	proto.RegisterType((*ReplyNetflowInfo)(nil), "omo.msp.third.ReplyNetflowInfo")
	proto.RegisterType((*ReplyNetflowList)(nil), "omo.msp.third.ReplyNetflowList")
}

func init() {
	proto.RegisterFile("proto/third/netflow.proto", fileDescriptor_bb66cca61b7c6432)
}

var fileDescriptor_bb66cca61b7c6432 = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0x9b, 0xfb, 0x91, 0xde, 0x4d, 0xbc, 0x52, 0x96, 0x2a, 0xeb, 0xa1, 0x78, 0xe4, 0xe9,
	0x9e, 0x52, 0xa8, 0xe0, 0x7b, 0x5b, 0xf0, 0xa8, 0x68, 0x85, 0x2d, 0xbe, 0x08, 0x3e, 0xa4, 0xc9,
	0xb4, 0x2e, 0x24, 0xd9, 0x34, 0x99, 0x54, 0xea, 0x3f, 0xe6, 0x7f, 0xe1, 0x93, 0xe0, 0xbf, 0x23,
	0xbb, 0x9b, 0x4b, 0xb7, 0x5c, 0xda, 0xaa, 0x6f, 0xf3, 0x9d, 0x99, 0xfd, 0xee, 0xce, 0x67, 0x42,
	0xe0, 0x79, 0x59, 0x29, 0x52, 0xfb, 0xf4, 0x55, 0x56, 0xe9, 0x7e, 0x81, 0x74, 0x91, 0xa9, 0x6f,
	0x91, 0xc9, 0xb1, 0x99, 0xca, 0x55, 0x94, 0xd7, 0x65, 0x64, 0x8a, 0x73, 0xee, 0x76, 0x26, 0x2a,
	0xcf, 0x55, 0x61, 0x1b, 0xc3, 0x1f, 0x03, 0x08, 0x4e, 0xed, 0xd1, 0x93, 0xe2, 0x42, 0xb1, 0x5d,
	0x18, 0x36, 0x32, 0xe5, 0xde, 0xc2, 0x5b, 0x4e, 0x85, 0x0e, 0xd9, 0x0e, 0x0c, 0x64, 0xca, 0x07,
	0x0b, 0x6f, 0x39, 0x12, 0x03, 0x99, 0x32, 0x06, 0x23, 0xba, 0x29, 0x91, 0x0f, 0x17, 0xde, 0x72,
	0x26, 0x4c, 0xcc, 0x38, 0x6c, 0x27, 0x15, 0xc6, 0x84, 0x29, 0x1f, 0x2d, 0xbc, 0xe5, 0x50, 0xac,
	0x65, 0x57, 0x51, 0x15, 0x1f, 0x1b, 0xcf, 0xb5, 0xd4, 0x3e, 0x45, 0x9c, 0x23, 0xf7, 0x4d, 0xda,
	0xc4, 0x6c, 0x0f, 0xc6, 0x57, 0x8d, 0x22, 0xe4, 0xdb, 0x26, 0x69, 0x85, 0xce, 0xd6, 0x09, 0x16,
	0xc8, 0x27, 0x36, 0x6b, 0x84, 0x3e, 0x5f, 0xcb, 0xef, 0xc8, 0xa7, 0xf6, 0x1d, 0x3a, 0x66, 0x73,
	0x98, 0x10, 0xe6, 0x65, 0x16, 0x13, 0x72, 0x30, 0xcd, 0x9d, 0x66, 0xcf, 0xc0, 0xa7, 0xb8, 0xba,
	0x44, 0xe2, 0x81, 0xa9, 0xb4, 0x8a, 0xbd, 0x81, 0x49, 0xa2, 0x0a, 0xc2, 0x82, 0x6a, 0xfe, 0x74,
	0x31, 0x5c, 0x06, 0x07, 0xf3, 0xe8, 0x0e, 0xbd, 0xe8, 0xd8, 0x96, 0x35, 0x1f, 0xd1, 0xf5, 0x86,
	0x5f, 0x20, 0x70, 0x0a, 0x3d, 0xe0, 0xd6, 0x0f, 0x1c, 0x38, 0x0f, 0xdc, 0x83, 0xf1, 0x65, 0xa5,
	0x9a, 0xd2, 0xd0, 0x9b, 0x0a, 0x2b, 0x3a, 0xa4, 0xa3, 0x5b, 0xa4, 0xe1, 0x6f, 0x0f, 0x66, 0x02,
	0xaf, 0xda, 0xdd, 0x1c, 0xa6, 0xfd, 0xe0, 0x3b, 0x34, 0x23, 0x17, 0xcd, 0x1c, 0x26, 0xaa, 0xc4,
	0xca, 0xa1, 0xde, 0xe9, 0x5b, 0xc4, 0xbe, 0x8b, 0xd8, 0x05, 0xb7, 0x7d, 0x2f, 0xb8, 0xc9, 0xbd,
	0xe0, 0x82, 0x7f, 0x00, 0x77, 0x0d, 0xbb, 0x02, 0xcb, 0xec, 0xc6, 0xfd, 0xec, 0x0e, 0xc0, 0xaf,
	0x29, 0xa6, 0xa6, 0x36, 0x00, 0x37, 0x9d, 0xcc, 0x81, 0x33, 0xd3, 0x21, 0xda, 0x4e, 0x16, 0xc1,
	0x48, 0x16, 0x17, 0xca, 0xf0, 0xdd, 0x3c, 0xe1, 0xb8, 0x0b, 0xd3, 0x17, 0xfe, 0xf4, 0xee, 0x5e,
	0xfc, 0x5e, 0xd6, 0xf4, 0x5f, 0x17, 0xef, 0xc1, 0x98, 0x14, 0xc5, 0x59, 0xbb, 0x59, 0x2b, 0x74,
	0xb6, 0x8c, 0x2f, 0xb1, 0x6e, 0xf7, 0x63, 0x85, 0x5e, 0x9a, 0x0e, 0xd6, 0xab, 0xd5, 0xb1, 0x06,
	0x5a, 0x34, 0xf9, 0x39, 0xda, 0xe5, 0xcc, 0x44, 0xab, 0xf4, 0x40, 0x99, 0xac, 0x89, 0xef, 0xf6,
	0xc2, 0xbc, 0x33, 0x90, 0xee, 0x3b, 0xf8, 0x35, 0x84, 0x9d, 0x36, 0x7b, 0x86, 0xd5, 0xb5, 0x4c,
	0x90, 0x9d, 0x80, 0x7f, 0x98, 0xa6, 0x1f, 0x0b, 0x64, 0x2f, 0x36, 0x06, 0x71, 0xbe, 0xa5, 0xf9,
	0xab, 0xbe, 0x31, 0x9d, 0x1b, 0xc2, 0x2d, 0xb6, 0x02, 0x7f, 0x85, 0xa4, 0xad, 0x36, 0x99, 0x5c,
	0x35, 0x58, 0x9b, 0xb5, 0xfe, 0x8d, 0xd1, 0x29, 0x04, 0x2b, 0xa4, 0xa3, 0x9b, 0xb7, 0x32, 0x23,
	0xac, 0xfa, 0x1e, 0xa6, 0xdd, 0x6c, 0xf5, 0x41, 0x3f, 0xbd, 0xb0, 0x70, 0x8b, 0x7d, 0x80, 0x27,
	0x2b, 0x24, 0xbd, 0x13, 0x59, 0x93, 0x4c, 0x1e, 0x31, 0x7c, 0x79, 0xdf, 0x42, 0xcd, 0xe1, 0x70,
	0x8b, 0xbd, 0x83, 0x9d, 0x4f, 0x65, 0x1a, 0x13, 0x3e, 0xf6, 0x42, 0xdb, 0x35, 0xe7, 0x7d, 0x86,
	0xed, 0xa8, 0xc7, 0x30, 0x15, 0x98, 0xab, 0x6b, 0x7c, 0x0c, 0xdb, 0x03, 0x26, 0x47, 0xb3, 0xcf,
	0x81, 0xf3, 0xbb, 0x3e, 0xf7, 0x8d, 0x78, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x5b, 0x4f,
	0x37, 0xee, 0x05, 0x00, 0x00,
}
