// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/third/partner.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PartnerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Phone                string   `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	Secret               string   `protobuf:"bytes,10,opt,name=secret,proto3" json:"secret,omitempty"`
	Tags                 []string `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartnerInfo) Reset()         { *m = PartnerInfo{} }
func (m *PartnerInfo) String() string { return proto.CompactTextString(m) }
func (*PartnerInfo) ProtoMessage()    {}
func (*PartnerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_539761bf7b178e7c, []int{0}
}

func (m *PartnerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartnerInfo.Unmarshal(m, b)
}
func (m *PartnerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartnerInfo.Marshal(b, m, deterministic)
}
func (m *PartnerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartnerInfo.Merge(m, src)
}
func (m *PartnerInfo) XXX_Size() int {
	return xxx_messageInfo_PartnerInfo.Size(m)
}
func (m *PartnerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartnerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartnerInfo proto.InternalMessageInfo

func (m *PartnerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PartnerInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PartnerInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PartnerInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *PartnerInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *PartnerInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *PartnerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PartnerInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *PartnerInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PartnerInfo) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *PartnerInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqPartnerAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Tags                 []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPartnerAdd) Reset()         { *m = ReqPartnerAdd{} }
func (m *ReqPartnerAdd) String() string { return proto.CompactTextString(m) }
func (*ReqPartnerAdd) ProtoMessage()    {}
func (*ReqPartnerAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_539761bf7b178e7c, []int{1}
}

func (m *ReqPartnerAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPartnerAdd.Unmarshal(m, b)
}
func (m *ReqPartnerAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPartnerAdd.Marshal(b, m, deterministic)
}
func (m *ReqPartnerAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPartnerAdd.Merge(m, src)
}
func (m *ReqPartnerAdd) XXX_Size() int {
	return xxx_messageInfo_ReqPartnerAdd.Size(m)
}
func (m *ReqPartnerAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPartnerAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPartnerAdd proto.InternalMessageInfo

func (m *ReqPartnerAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqPartnerAdd) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ReqPartnerAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqPartnerAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqPartnerAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqPartnerUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Operator             string   `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPartnerUpdate) Reset()         { *m = ReqPartnerUpdate{} }
func (m *ReqPartnerUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqPartnerUpdate) ProtoMessage()    {}
func (*ReqPartnerUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_539761bf7b178e7c, []int{2}
}

func (m *ReqPartnerUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPartnerUpdate.Unmarshal(m, b)
}
func (m *ReqPartnerUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPartnerUpdate.Marshal(b, m, deterministic)
}
func (m *ReqPartnerUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPartnerUpdate.Merge(m, src)
}
func (m *ReqPartnerUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqPartnerUpdate.Size(m)
}
func (m *ReqPartnerUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPartnerUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPartnerUpdate proto.InternalMessageInfo

func (m *ReqPartnerUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqPartnerUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqPartnerUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqPartnerUpdate) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ReqPartnerUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqPartnerTags struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPartnerTags) Reset()         { *m = ReqPartnerTags{} }
func (m *ReqPartnerTags) String() string { return proto.CompactTextString(m) }
func (*ReqPartnerTags) ProtoMessage()    {}
func (*ReqPartnerTags) Descriptor() ([]byte, []int) {
	return fileDescriptor_539761bf7b178e7c, []int{3}
}

func (m *ReqPartnerTags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPartnerTags.Unmarshal(m, b)
}
func (m *ReqPartnerTags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPartnerTags.Marshal(b, m, deterministic)
}
func (m *ReqPartnerTags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPartnerTags.Merge(m, src)
}
func (m *ReqPartnerTags) XXX_Size() int {
	return xxx_messageInfo_ReqPartnerTags.Size(m)
}
func (m *ReqPartnerTags) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPartnerTags.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPartnerTags proto.InternalMessageInfo

func (m *ReqPartnerTags) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqPartnerTags) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqPartnerTags) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReplyPartnerInfo struct {
	Info                 *PartnerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyPartnerInfo) Reset()         { *m = ReplyPartnerInfo{} }
func (m *ReplyPartnerInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyPartnerInfo) ProtoMessage()    {}
func (*ReplyPartnerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_539761bf7b178e7c, []int{4}
}

func (m *ReplyPartnerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPartnerInfo.Unmarshal(m, b)
}
func (m *ReplyPartnerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPartnerInfo.Marshal(b, m, deterministic)
}
func (m *ReplyPartnerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPartnerInfo.Merge(m, src)
}
func (m *ReplyPartnerInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyPartnerInfo.Size(m)
}
func (m *ReplyPartnerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPartnerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPartnerInfo proto.InternalMessageInfo

func (m *ReplyPartnerInfo) GetInfo() *PartnerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyPartnerInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReqPartnerList struct {
	List                 []string `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPartnerList) Reset()         { *m = ReqPartnerList{} }
func (m *ReqPartnerList) String() string { return proto.CompactTextString(m) }
func (*ReqPartnerList) ProtoMessage()    {}
func (*ReqPartnerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_539761bf7b178e7c, []int{5}
}

func (m *ReqPartnerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPartnerList.Unmarshal(m, b)
}
func (m *ReqPartnerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPartnerList.Marshal(b, m, deterministic)
}
func (m *ReqPartnerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPartnerList.Merge(m, src)
}
func (m *ReqPartnerList) XXX_Size() int {
	return xxx_messageInfo_ReqPartnerList.Size(m)
}
func (m *ReqPartnerList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPartnerList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPartnerList proto.InternalMessageInfo

func (m *ReqPartnerList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyPartnerSecret struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Uid                  string       `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Secret               string       `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyPartnerSecret) Reset()         { *m = ReplyPartnerSecret{} }
func (m *ReplyPartnerSecret) String() string { return proto.CompactTextString(m) }
func (*ReplyPartnerSecret) ProtoMessage()    {}
func (*ReplyPartnerSecret) Descriptor() ([]byte, []int) {
	return fileDescriptor_539761bf7b178e7c, []int{6}
}

func (m *ReplyPartnerSecret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPartnerSecret.Unmarshal(m, b)
}
func (m *ReplyPartnerSecret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPartnerSecret.Marshal(b, m, deterministic)
}
func (m *ReplyPartnerSecret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPartnerSecret.Merge(m, src)
}
func (m *ReplyPartnerSecret) XXX_Size() int {
	return xxx_messageInfo_ReplyPartnerSecret.Size(m)
}
func (m *ReplyPartnerSecret) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPartnerSecret.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPartnerSecret proto.InternalMessageInfo

func (m *ReplyPartnerSecret) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyPartnerSecret) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyPartnerSecret) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type ReplyPartnerList struct {
	Total                uint64         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32         `protobuf:"varint,2,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32         `protobuf:"varint,3,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*PartnerInfo `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyPartnerList) Reset()         { *m = ReplyPartnerList{} }
func (m *ReplyPartnerList) String() string { return proto.CompactTextString(m) }
func (*ReplyPartnerList) ProtoMessage()    {}
func (*ReplyPartnerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_539761bf7b178e7c, []int{7}
}

func (m *ReplyPartnerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyPartnerList.Unmarshal(m, b)
}
func (m *ReplyPartnerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyPartnerList.Marshal(b, m, deterministic)
}
func (m *ReplyPartnerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyPartnerList.Merge(m, src)
}
func (m *ReplyPartnerList) XXX_Size() int {
	return xxx_messageInfo_ReplyPartnerList.Size(m)
}
func (m *ReplyPartnerList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyPartnerList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyPartnerList proto.InternalMessageInfo

func (m *ReplyPartnerList) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyPartnerList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyPartnerList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyPartnerList) GetList() []*PartnerInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyPartnerList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*PartnerInfo)(nil), "omo.msp.third.PartnerInfo")
	proto.RegisterType((*ReqPartnerAdd)(nil), "omo.msp.third.ReqPartnerAdd")
	proto.RegisterType((*ReqPartnerUpdate)(nil), "omo.msp.third.ReqPartnerUpdate")
	proto.RegisterType((*ReqPartnerTags)(nil), "omo.msp.third.ReqPartnerTags")
	proto.RegisterType((*ReplyPartnerInfo)(nil), "omo.msp.third.ReplyPartnerInfo")
	proto.RegisterType((*ReqPartnerList)(nil), "omo.msp.third.ReqPartnerList")
	proto.RegisterType((*ReplyPartnerSecret)(nil), "omo.msp.third.ReplyPartnerSecret")
	proto.RegisterType((*ReplyPartnerList)(nil), "omo.msp.third.ReplyPartnerList")
}

func init() {
	proto.RegisterFile("proto/third/partner.proto", fileDescriptor_539761bf7b178e7c)
}

var fileDescriptor_539761bf7b178e7c = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcf, 0x6e, 0xda, 0x4e,
	0x10, 0x8e, 0xff, 0xe0, 0xc0, 0xf0, 0x03, 0x45, 0xab, 0xe8, 0xa7, 0x2d, 0xaa, 0x54, 0x6a, 0xf5,
	0xc0, 0xc9, 0x91, 0xe8, 0x13, 0x24, 0x39, 0xd0, 0x54, 0x69, 0x12, 0x39, 0xed, 0xa5, 0x37, 0x17,
	0x6f, 0x88, 0x55, 0xec, 0x75, 0xd6, 0x0b, 0x69, 0x8e, 0xed, 0xa5, 0x6f, 0xd1, 0x67, 0xe9, 0xa3,
	0x55, 0x3b, 0x6b, 0x9b, 0xa5, 0x38, 0xc0, 0xa1, 0xb7, 0x9d, 0x9d, 0x99, 0x6f, 0xbe, 0xef, 0xf3,
	0x2c, 0xc0, 0x8b, 0x5c, 0x70, 0xc9, 0x4f, 0xe4, 0x7d, 0x22, 0xe2, 0x93, 0x3c, 0x12, 0x32, 0x63,
	0x22, 0xc0, 0x3b, 0xd2, 0xe3, 0x29, 0x0f, 0xd2, 0x22, 0x0f, 0x30, 0x39, 0xa0, 0x66, 0xe5, 0x94,
	0xa7, 0x29, 0xcf, 0x74, 0xa1, 0xff, 0xd3, 0x86, 0xee, 0x8d, 0x6e, 0xbd, 0xc8, 0xee, 0x38, 0x39,
	0x02, 0x67, 0x91, 0xc4, 0xd4, 0x1a, 0x5a, 0xa3, 0x4e, 0xa8, 0x8e, 0xa4, 0x0f, 0x76, 0x12, 0x53,
	0x7b, 0x68, 0x8d, 0xdc, 0xd0, 0x4e, 0x62, 0x42, 0xe1, 0x70, 0x2a, 0x58, 0x24, 0x59, 0x4c, 0x9d,
	0xa1, 0x35, 0x72, 0xc2, 0x2a, 0x54, 0x99, 0x45, 0x1e, 0x63, 0xc6, 0xd5, 0x99, 0x32, 0xac, 0x7b,
	0xb8, 0xa0, 0x2d, 0x44, 0xae, 0x42, 0x32, 0x80, 0x36, 0xcf, 0x99, 0xc0, 0x94, 0x87, 0xa9, 0x3a,
	0x26, 0x04, 0xdc, 0x2c, 0x4a, 0x19, 0x3d, 0xc4, 0x7b, 0x3c, 0x93, 0xff, 0xc1, 0x13, 0x2c, 0x8d,
	0xc4, 0x57, 0xda, 0xc6, 0xdb, 0x32, 0x22, 0xc7, 0xd0, 0xca, 0xef, 0x79, 0xc6, 0x68, 0x07, 0xaf,
	0x75, 0xa0, 0xaa, 0x0b, 0x36, 0x15, 0x4c, 0x52, 0xd0, 0xd5, 0x3a, 0x52, 0xc8, 0x32, 0x9a, 0x15,
	0xb4, 0x3b, 0x74, 0x14, 0xb2, 0x3a, 0xfb, 0xdf, 0x2d, 0xe8, 0x85, 0xec, 0xa1, 0x34, 0xe3, 0x34,
	0x8e, 0xeb, 0xf9, 0x96, 0x31, 0xbf, 0x9e, 0x63, 0xff, 0x35, 0xa7, 0x64, 0xe5, 0xac, 0xb1, 0x32,
	0xd5, 0xb9, 0x9b, 0xea, 0x90, 0x43, 0xcb, 0xe0, 0xf0, 0xc3, 0x82, 0xa3, 0x15, 0x87, 0x4f, 0xe8,
	0x5e, 0xc3, 0x27, 0xa9, 0x88, 0xd9, 0x8d, 0xc6, 0x38, 0xcd, 0xc6, 0xb8, 0x26, 0x61, 0x93, 0x58,
	0x7b, 0x9d, 0x98, 0x1f, 0x42, 0x7f, 0xc5, 0xe1, 0x63, 0x34, 0x2b, 0x1a, 0x18, 0x98, 0xfd, 0xf6,
	0x33, 0xc2, 0x1c, 0x43, 0xd8, 0x52, 0xe9, 0xca, 0xe7, 0x4f, 0xe6, 0xaa, 0x05, 0xe0, 0x26, 0xd9,
	0x1d, 0x47, 0xd8, 0xee, 0x78, 0x10, 0xac, 0xad, 0x6c, 0x60, 0x54, 0x86, 0x58, 0x47, 0xc6, 0xe0,
	0x15, 0x32, 0x92, 0x8b, 0x02, 0x27, 0x6e, 0x76, 0xe0, 0x80, 0x5b, 0xac, 0x08, 0xcb, 0x4a, 0xff,
	0x8d, 0xa9, 0xe5, 0x32, 0x29, 0xf0, 0xd3, 0xcf, 0x93, 0x42, 0x52, 0x57, 0xb3, 0x53, 0x67, 0x5f,
	0x00, 0x31, 0xd9, 0xdd, 0xea, 0x25, 0x59, 0xcd, 0xb3, 0xf6, 0x9d, 0x57, 0x39, 0x65, 0xaf, 0x9c,
	0x5a, 0xad, 0xa0, 0x63, 0xae, 0xa0, 0xff, 0xdb, 0x5a, 0xb7, 0x04, 0xc9, 0x1d, 0x43, 0x4b, 0x72,
	0x19, 0xcd, 0x71, 0xa2, 0x1b, 0xea, 0x40, 0xbd, 0x9e, 0x3c, 0x9a, 0xb1, 0x0f, 0xd1, 0x37, 0x04,
	0xee, 0x85, 0x55, 0x58, 0x65, 0xae, 0xf8, 0x23, 0xa2, 0x97, 0x99, 0x2b, 0xfe, 0xa8, 0xcc, 0xad,
	0x65, 0xee, 0x30, 0x57, 0xd5, 0x19, 0x62, 0x5b, 0xfb, 0x8a, 0x1d, 0xff, 0x72, 0xa1, 0x5f, 0x5b,
	0x26, 0x96, 0xc9, 0x94, 0x91, 0x0b, 0xf0, 0x4e, 0xe3, 0xf8, 0x3a, 0x63, 0xe4, 0xe5, 0x06, 0x80,
	0xf1, 0xb4, 0x06, 0xaf, 0x9a, 0xe0, 0x0d, 0x56, 0xfe, 0x01, 0x99, 0x80, 0x37, 0x61, 0x52, 0x41,
	0x6d, 0x72, 0x79, 0x58, 0xb0, 0x42, 0xaa, 0xba, 0x7d, 0x80, 0xde, 0xc1, 0xe1, 0x84, 0x49, 0xf4,
	0xf7, 0x19, 0xa4, 0x9b, 0x68, 0xc6, 0xb6, 0x22, 0xa9, 0x66, 0xff, 0x80, 0xbc, 0x87, 0x8e, 0x7e,
	0x93, 0xff, 0x80, 0xd5, 0x39, 0x74, 0x42, 0x96, 0xf2, 0xe5, 0x4e, 0x2c, 0xda, 0x84, 0x55, 0x82,
	0x5c, 0xc3, 0x7f, 0xe7, 0xf8, 0xe3, 0x5b, 0xae, 0xec, 0x36, 0x9c, 0xd7, 0x5b, 0x38, 0xe9, 0x76,
	0xff, 0x80, 0x5c, 0x42, 0x77, 0xc2, 0xe4, 0xd9, 0xd3, 0x1e, 0x78, 0xbb, 0x35, 0x9e, 0xf5, 0x3e,
	0x77, 0x8d, 0x3f, 0x9e, 0x2f, 0x1e, 0x06, 0x6f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x66, 0xdc,
	0xca, 0xdc, 0xb8, 0x06, 0x00, 0x00,
}
