// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/third/record.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecordInfo struct {
	Uid                  string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64         `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 uint32         `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Created              int64          `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Creator              string         `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Name                 string         `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Quote                string         `protobuf:"bytes,7,opt,name=quote,proto3" json:"quote,omitempty"`
	Scene                string         `protobuf:"bytes,8,opt,name=scene,proto3" json:"scene,omitempty"`
	Size                 uint32         `protobuf:"varint,9,opt,name=size,proto3" json:"size,omitempty"`
	Template             string         `protobuf:"bytes,10,opt,name=template,proto3" json:"template,omitempty"`
	Target               string         `protobuf:"bytes,11,opt,name=target,proto3" json:"target,omitempty"`
	Contents             []*ContentInfo `protobuf:"bytes,21,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RecordInfo) Reset()         { *m = RecordInfo{} }
func (m *RecordInfo) String() string { return proto.CompactTextString(m) }
func (*RecordInfo) ProtoMessage()    {}
func (*RecordInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c5954b907daad2a, []int{0}
}

func (m *RecordInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordInfo.Unmarshal(m, b)
}
func (m *RecordInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordInfo.Marshal(b, m, deterministic)
}
func (m *RecordInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordInfo.Merge(m, src)
}
func (m *RecordInfo) XXX_Size() int {
	return xxx_messageInfo_RecordInfo.Size(m)
}
func (m *RecordInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RecordInfo proto.InternalMessageInfo

func (m *RecordInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RecordInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RecordInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RecordInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *RecordInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *RecordInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecordInfo) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *RecordInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *RecordInfo) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RecordInfo) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *RecordInfo) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *RecordInfo) GetContents() []*ContentInfo {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ContentInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Events               []string `protobuf:"bytes,10,rep,name=events,proto3" json:"events,omitempty"`
	Assets               []string `protobuf:"bytes,11,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentInfo) Reset()         { *m = ContentInfo{} }
func (m *ContentInfo) String() string { return proto.CompactTextString(m) }
func (*ContentInfo) ProtoMessage()    {}
func (*ContentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c5954b907daad2a, []int{1}
}

func (m *ContentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentInfo.Unmarshal(m, b)
}
func (m *ContentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentInfo.Marshal(b, m, deterministic)
}
func (m *ContentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentInfo.Merge(m, src)
}
func (m *ContentInfo) XXX_Size() int {
	return xxx_messageInfo_ContentInfo.Size(m)
}
func (m *ContentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContentInfo proto.InternalMessageInfo

func (m *ContentInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ContentInfo) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ContentInfo) GetEvents() []string {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *ContentInfo) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

type ReqRecordAdd struct {
	Type                 uint32         `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Scene                string         `protobuf:"bytes,4,opt,name=scene,proto3" json:"scene,omitempty"`
	Operator             string         `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Quote                string         `protobuf:"bytes,6,opt,name=quote,proto3" json:"quote,omitempty"`
	Template             string         `protobuf:"bytes,7,opt,name=template,proto3" json:"template,omitempty"`
	Target               string         `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	Contents             []*ContentInfo `protobuf:"bytes,11,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReqRecordAdd) Reset()         { *m = ReqRecordAdd{} }
func (m *ReqRecordAdd) String() string { return proto.CompactTextString(m) }
func (*ReqRecordAdd) ProtoMessage()    {}
func (*ReqRecordAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c5954b907daad2a, []int{2}
}

func (m *ReqRecordAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRecordAdd.Unmarshal(m, b)
}
func (m *ReqRecordAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRecordAdd.Marshal(b, m, deterministic)
}
func (m *ReqRecordAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRecordAdd.Merge(m, src)
}
func (m *ReqRecordAdd) XXX_Size() int {
	return xxx_messageInfo_ReqRecordAdd.Size(m)
}
func (m *ReqRecordAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRecordAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRecordAdd proto.InternalMessageInfo

func (m *ReqRecordAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqRecordAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqRecordAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqRecordAdd) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *ReqRecordAdd) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *ReqRecordAdd) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ReqRecordAdd) GetContents() []*ContentInfo {
	if m != nil {
		return m.Contents
	}
	return nil
}

type ReplyRecordInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *RecordInfo  `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyRecordInfo) Reset()         { *m = ReplyRecordInfo{} }
func (m *ReplyRecordInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyRecordInfo) ProtoMessage()    {}
func (*ReplyRecordInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c5954b907daad2a, []int{3}
}

func (m *ReplyRecordInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRecordInfo.Unmarshal(m, b)
}
func (m *ReplyRecordInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRecordInfo.Marshal(b, m, deterministic)
}
func (m *ReplyRecordInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRecordInfo.Merge(m, src)
}
func (m *ReplyRecordInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyRecordInfo.Size(m)
}
func (m *ReplyRecordInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRecordInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRecordInfo proto.InternalMessageInfo

func (m *ReplyRecordInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyRecordInfo) GetInfo() *RecordInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyRecordList struct {
	Status               *ReplyStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32        `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32        `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32        `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*RecordInfo `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyRecordList) Reset()         { *m = ReplyRecordList{} }
func (m *ReplyRecordList) String() string { return proto.CompactTextString(m) }
func (*ReplyRecordList) ProtoMessage()    {}
func (*ReplyRecordList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c5954b907daad2a, []int{4}
}

func (m *ReplyRecordList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRecordList.Unmarshal(m, b)
}
func (m *ReplyRecordList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRecordList.Marshal(b, m, deterministic)
}
func (m *ReplyRecordList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRecordList.Merge(m, src)
}
func (m *ReplyRecordList) XXX_Size() int {
	return xxx_messageInfo_ReplyRecordList.Size(m)
}
func (m *ReplyRecordList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRecordList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRecordList proto.InternalMessageInfo

func (m *ReplyRecordList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyRecordList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyRecordList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyRecordList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyRecordList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyRecordList) GetList() []*RecordInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*RecordInfo)(nil), "omo.msp.third.RecordInfo")
	proto.RegisterType((*ContentInfo)(nil), "omo.msp.third.ContentInfo")
	proto.RegisterType((*ReqRecordAdd)(nil), "omo.msp.third.ReqRecordAdd")
	proto.RegisterType((*ReplyRecordInfo)(nil), "omo.msp.third.ReplyRecordInfo")
	proto.RegisterType((*ReplyRecordList)(nil), "omo.msp.third.ReplyRecordList")
}

func init() {
	proto.RegisterFile("proto/third/record.proto", fileDescriptor_2c5954b907daad2a)
}

var fileDescriptor_2c5954b907daad2a = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x6b, 0xdb, 0x4e,
	0x10, 0x8d, 0x6c, 0x47, 0x71, 0x46, 0x71, 0x7e, 0x61, 0xc9, 0x2f, 0x6c, 0xdd, 0x3f, 0x08, 0x9d,
	0x7c, 0xa9, 0x03, 0x2e, 0xf4, 0x9e, 0x04, 0x62, 0x5a, 0x5a, 0x0a, 0x1b, 0x7a, 0xe9, 0x4d, 0x91,
	0x26, 0xe9, 0x82, 0xa5, 0x55, 0xb4, 0xe3, 0x40, 0xfa, 0xc1, 0xfa, 0x29, 0x0a, 0xbd, 0xf5, 0xf3,
	0x94, 0x9d, 0x95, 0x1d, 0x05, 0x3b, 0x71, 0xdb, 0xdb, 0xbc, 0x99, 0xb7, 0x6f, 0x67, 0xdf, 0x13,
	0x02, 0x59, 0xd5, 0x86, 0xcc, 0x31, 0x7d, 0xd5, 0x75, 0x7e, 0x5c, 0x63, 0x66, 0xea, 0x7c, 0xcc,
	0x2d, 0x31, 0x30, 0x85, 0x19, 0x17, 0xb6, 0x1a, 0xf3, 0x6c, 0xf8, 0x80, 0x98, 0x99, 0xa2, 0x30,
	0xa5, 0x27, 0x26, 0xdf, 0x3b, 0x00, 0x8a, 0x4f, 0xbe, 0x2b, 0xaf, 0x8c, 0x38, 0x80, 0xee, 0x5c,
	0xe7, 0x32, 0x88, 0x83, 0xd1, 0xae, 0x72, 0xa5, 0xd8, 0x87, 0x8e, 0xce, 0x65, 0x27, 0x0e, 0x46,
	0x3d, 0xd5, 0xd1, 0xb9, 0x10, 0xd0, 0xa3, 0xbb, 0x0a, 0x65, 0x37, 0x0e, 0x46, 0x03, 0xc5, 0xb5,
	0x90, 0xb0, 0x93, 0xd5, 0x98, 0x12, 0xe6, 0xb2, 0x17, 0x07, 0xa3, 0xae, 0x5a, 0xc0, 0xe5, 0xc4,
	0xd4, 0x72, 0x9b, 0x35, 0x17, 0xd0, 0xe9, 0x94, 0x69, 0x81, 0x32, 0xe4, 0x36, 0xd7, 0xe2, 0x10,
	0xb6, 0x6f, 0xe6, 0x86, 0x50, 0xee, 0x70, 0xd3, 0x03, 0xd7, 0xb5, 0x19, 0x96, 0x28, 0xfb, 0xbe,
	0xcb, 0xc0, 0x9d, 0xb7, 0xfa, 0x1b, 0xca, 0x5d, 0xbf, 0x87, 0xab, 0xc5, 0x10, 0xfa, 0x84, 0x45,
	0x35, 0x4b, 0x09, 0x25, 0x30, 0x79, 0x89, 0xc5, 0x11, 0x84, 0x94, 0xd6, 0xd7, 0x48, 0x32, 0xe2,
	0x49, 0x83, 0xc4, 0x5b, 0xe8, 0x67, 0xa6, 0x24, 0x2c, 0xc9, 0xca, 0xff, 0xe3, 0xee, 0x28, 0x9a,
	0x0c, 0xc7, 0x0f, 0xcc, 0x1b, 0x9f, 0xf9, 0xb1, 0xf3, 0x47, 0x2d, 0xb9, 0x49, 0x06, 0x51, 0x6b,
	0xb0, 0xc6, 0xb8, 0xc5, 0x82, 0x9d, 0xd6, 0x82, 0x47, 0x10, 0xe2, 0x2d, 0x5f, 0x05, 0x71, 0xd7,
	0x2d, 0xe1, 0x91, 0xeb, 0xa7, 0xd6, 0x22, 0x59, 0x19, 0xf9, 0xbe, 0x47, 0xc9, 0xaf, 0x00, 0xf6,
	0x14, 0xde, 0xf8, 0x80, 0x4e, 0xf2, 0xf5, 0xee, 0x2f, 0xfd, 0xe9, 0xb5, 0xfd, 0x19, 0x42, 0xdf,
	0x54, 0x58, 0xb7, 0xac, 0x5f, 0xe2, 0x7b, 0x9f, 0xc3, 0xb6, 0xcf, 0x6d, 0xf7, 0x76, 0x1e, 0x75,
	0xaf, 0xff, 0xa8, 0x7b, 0xd1, 0x5f, 0xb8, 0x47, 0xf0, 0x9f, 0xc2, 0x6a, 0x76, 0xd7, 0xfa, 0xf4,
	0x26, 0x10, 0x5a, 0x4a, 0x69, 0x6e, 0xd9, 0xc4, 0x55, 0x21, 0xe6, 0x5f, 0x30, 0x43, 0x35, 0x4c,
	0xf1, 0x1a, 0x7a, 0xba, 0xbc, 0x32, 0xec, 0x71, 0x34, 0x79, 0xb6, 0x72, 0x62, 0x21, 0xae, 0x98,
	0x96, 0xfc, 0x08, 0x1e, 0x5c, 0xfb, 0x41, 0x5b, 0xfa, 0xa7, 0x6b, 0x0f, 0x61, 0x9b, 0x0c, 0xa5,
	0xb3, 0x26, 0x5b, 0x0f, 0x5c, 0xb7, 0x4a, 0xaf, 0xd1, 0x36, 0xe1, 0x78, 0xe0, 0x12, 0x73, 0x05,
	0x87, 0x33, 0x50, 0x5c, 0x3b, 0x37, 0xcb, 0x79, 0x71, 0x89, 0x3e, 0x99, 0x81, 0x6a, 0x90, 0x7b,
	0xce, 0x4c, 0x5b, 0x92, 0x07, 0xec, 0xe4, 0x53, 0xcf, 0x71, 0xb4, 0xc9, 0xcf, 0x2e, 0x0c, 0x7c,
	0xf3, 0x02, 0xeb, 0x5b, 0x9d, 0xa1, 0x98, 0x42, 0x78, 0x92, 0xe7, 0x9f, 0x4a, 0x14, 0xcf, 0x57,
	0x0e, 0xdf, 0x7f, 0x45, 0xc3, 0x57, 0xeb, 0xde, 0x78, 0x2f, 0x9f, 0x6c, 0x89, 0x73, 0x08, 0xa7,
	0x48, 0x4e, 0x68, 0xd5, 0x8f, 0x9b, 0x39, 0x5a, 0xce, 0xf3, 0x0f, 0x74, 0x3e, 0x42, 0x34, 0x45,
	0x3a, 0xbd, 0x3b, 0xd7, 0x33, 0xc2, 0x5a, 0xbc, 0x58, 0x2f, 0xe6, 0xa7, 0x4f, 0xc9, 0xb9, 0xa8,
	0x58, 0x6e, 0x6f, 0x8a, 0xe4, 0xd2, 0xd0, 0x96, 0x74, 0xb6, 0x41, 0xef, 0xe5, 0x63, 0x51, 0xf2,
	0xe1, 0x64, 0x4b, 0xbc, 0x87, 0xfd, 0xcf, 0x55, 0x9e, 0x12, 0x6e, 0x5a, 0xd0, 0xb3, 0x86, 0x72,
	0x9d, 0x60, 0xf3, 0xd2, 0x33, 0xd8, 0x55, 0x58, 0x98, 0x5b, 0xdc, 0x64, 0xda, 0x13, 0x22, 0xa7,
	0x83, 0x2f, 0x51, 0xeb, 0x4f, 0x7d, 0x19, 0x32, 0x78, 0xf3, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0xa2, 0x1c, 0xe9, 0xe8, 0x05, 0x00, 0x00,
}
