// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/third/record.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RecordService service

type RecordService interface {
	AddOne(ctx context.Context, in *ReqRecordAdd, opts ...client.CallOption) (*ReplyRecordInfo, error)
	GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyRecordInfo, error)
	GetByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyRecordList, error)
	GetStatistic(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStatistic, error)
	UpdateByFilter(ctx context.Context, in *RequestUpdate, opts ...client.CallOption) (*ReplyInfo, error)
	RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error)
}

type recordService struct {
	c    client.Client
	name string
}

func NewRecordService(name string, c client.Client) RecordService {
	return &recordService{
		c:    c,
		name: name,
	}
}

func (c *recordService) AddOne(ctx context.Context, in *ReqRecordAdd, opts ...client.CallOption) (*ReplyRecordInfo, error) {
	req := c.c.NewRequest(c.name, "RecordService.AddOne", in)
	out := new(ReplyRecordInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordService) GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyRecordInfo, error) {
	req := c.c.NewRequest(c.name, "RecordService.GetOne", in)
	out := new(ReplyRecordInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordService) GetByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyRecordList, error) {
	req := c.c.NewRequest(c.name, "RecordService.GetByFilter", in)
	out := new(ReplyRecordList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordService) GetStatistic(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStatistic, error) {
	req := c.c.NewRequest(c.name, "RecordService.GetStatistic", in)
	out := new(ReplyStatistic)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordService) UpdateByFilter(ctx context.Context, in *RequestUpdate, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "RecordService.UpdateByFilter", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordService) RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "RecordService.RemoveOne", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RecordService service

type RecordServiceHandler interface {
	AddOne(context.Context, *ReqRecordAdd, *ReplyRecordInfo) error
	GetOne(context.Context, *RequestInfo, *ReplyRecordInfo) error
	GetByFilter(context.Context, *RequestFilter, *ReplyRecordList) error
	GetStatistic(context.Context, *RequestFilter, *ReplyStatistic) error
	UpdateByFilter(context.Context, *RequestUpdate, *ReplyInfo) error
	RemoveOne(context.Context, *RequestInfo, *ReplyInfo) error
}

func RegisterRecordServiceHandler(s server.Server, hdlr RecordServiceHandler, opts ...server.HandlerOption) error {
	type recordService interface {
		AddOne(ctx context.Context, in *ReqRecordAdd, out *ReplyRecordInfo) error
		GetOne(ctx context.Context, in *RequestInfo, out *ReplyRecordInfo) error
		GetByFilter(ctx context.Context, in *RequestFilter, out *ReplyRecordList) error
		GetStatistic(ctx context.Context, in *RequestFilter, out *ReplyStatistic) error
		UpdateByFilter(ctx context.Context, in *RequestUpdate, out *ReplyInfo) error
		RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error
	}
	type RecordService struct {
		recordService
	}
	h := &recordServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RecordService{h}, opts...))
}

type recordServiceHandler struct {
	RecordServiceHandler
}

func (h *recordServiceHandler) AddOne(ctx context.Context, in *ReqRecordAdd, out *ReplyRecordInfo) error {
	return h.RecordServiceHandler.AddOne(ctx, in, out)
}

func (h *recordServiceHandler) GetOne(ctx context.Context, in *RequestInfo, out *ReplyRecordInfo) error {
	return h.RecordServiceHandler.GetOne(ctx, in, out)
}

func (h *recordServiceHandler) GetByFilter(ctx context.Context, in *RequestFilter, out *ReplyRecordList) error {
	return h.RecordServiceHandler.GetByFilter(ctx, in, out)
}

func (h *recordServiceHandler) GetStatistic(ctx context.Context, in *RequestFilter, out *ReplyStatistic) error {
	return h.RecordServiceHandler.GetStatistic(ctx, in, out)
}

func (h *recordServiceHandler) UpdateByFilter(ctx context.Context, in *RequestUpdate, out *ReplyInfo) error {
	return h.RecordServiceHandler.UpdateByFilter(ctx, in, out)
}

func (h *recordServiceHandler) RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error {
	return h.RecordServiceHandler.RemoveOne(ctx, in, out)
}
