// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/third/reserve.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReserveInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Scene                string   `protobuf:"bytes,9,opt,name=scene,proto3" json:"scene,omitempty"`
	Contact              string   `protobuf:"bytes,10,opt,name=contact,proto3" json:"contact,omitempty"`
	Count                uint32   `protobuf:"varint,11,opt,name=count,proto3" json:"count,omitempty"`
	Date                 string   `protobuf:"bytes,12,opt,name=date,proto3" json:"date,omitempty"`
	Type                 uint32   `protobuf:"varint,13,opt,name=type,proto3" json:"type,omitempty"`
	Status               uint32   `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	Uint                 string   `protobuf:"bytes,15,opt,name=uint,proto3" json:"uint,omitempty"`
	Begin                uint32   `protobuf:"varint,16,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  uint32   `protobuf:"varint,17,opt,name=end,proto3" json:"end,omitempty"`
	Card                 string   `protobuf:"bytes,18,opt,name=card,proto3" json:"card,omitempty"`
	Assets               []string `protobuf:"bytes,21,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveInfo) Reset()         { *m = ReserveInfo{} }
func (m *ReserveInfo) String() string { return proto.CompactTextString(m) }
func (*ReserveInfo) ProtoMessage()    {}
func (*ReserveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec66a507dd698ded, []int{0}
}

func (m *ReserveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveInfo.Unmarshal(m, b)
}
func (m *ReserveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveInfo.Marshal(b, m, deterministic)
}
func (m *ReserveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveInfo.Merge(m, src)
}
func (m *ReserveInfo) XXX_Size() int {
	return xxx_messageInfo_ReserveInfo.Size(m)
}
func (m *ReserveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveInfo proto.InternalMessageInfo

func (m *ReserveInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReserveInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReserveInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ReserveInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ReserveInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ReserveInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReserveInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReserveInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReserveInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReserveInfo) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *ReserveInfo) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReserveInfo) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ReserveInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReserveInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReserveInfo) GetUint() string {
	if m != nil {
		return m.Uint
	}
	return ""
}

func (m *ReserveInfo) GetBegin() uint32 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *ReserveInfo) GetEnd() uint32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *ReserveInfo) GetCard() string {
	if m != nil {
		return m.Card
	}
	return ""
}

func (m *ReserveInfo) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

type ReqReserveAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Contact              string   `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Scene                string   `protobuf:"bytes,5,opt,name=scene,proto3" json:"scene,omitempty"`
	Kind                 uint32   `protobuf:"varint,6,opt,name=kind,proto3" json:"kind,omitempty"`
	Count                uint32   `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	Uint                 string   `protobuf:"bytes,8,opt,name=uint,proto3" json:"uint,omitempty"`
	Date                 string   `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty"`
	Begin                uint32   `protobuf:"varint,10,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  uint32   `protobuf:"varint,11,opt,name=end,proto3" json:"end,omitempty"`
	Card                 string   `protobuf:"bytes,12,opt,name=card,proto3" json:"card,omitempty"`
	Assets               []string `protobuf:"bytes,21,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqReserveAdd) Reset()         { *m = ReqReserveAdd{} }
func (m *ReqReserveAdd) String() string { return proto.CompactTextString(m) }
func (*ReqReserveAdd) ProtoMessage()    {}
func (*ReqReserveAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec66a507dd698ded, []int{1}
}

func (m *ReqReserveAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqReserveAdd.Unmarshal(m, b)
}
func (m *ReqReserveAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqReserveAdd.Marshal(b, m, deterministic)
}
func (m *ReqReserveAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqReserveAdd.Merge(m, src)
}
func (m *ReqReserveAdd) XXX_Size() int {
	return xxx_messageInfo_ReqReserveAdd.Size(m)
}
func (m *ReqReserveAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqReserveAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqReserveAdd proto.InternalMessageInfo

func (m *ReqReserveAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqReserveAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqReserveAdd) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *ReqReserveAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqReserveAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqReserveAdd) GetKind() uint32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *ReqReserveAdd) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReqReserveAdd) GetUint() string {
	if m != nil {
		return m.Uint
	}
	return ""
}

func (m *ReqReserveAdd) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ReqReserveAdd) GetBegin() uint32 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *ReqReserveAdd) GetEnd() uint32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *ReqReserveAdd) GetCard() string {
	if m != nil {
		return m.Card
	}
	return ""
}

func (m *ReqReserveAdd) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

type ReplyReserveInfo struct {
	Info                 *ReserveInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyReserveInfo) Reset()         { *m = ReplyReserveInfo{} }
func (m *ReplyReserveInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyReserveInfo) ProtoMessage()    {}
func (*ReplyReserveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec66a507dd698ded, []int{2}
}

func (m *ReplyReserveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyReserveInfo.Unmarshal(m, b)
}
func (m *ReplyReserveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyReserveInfo.Marshal(b, m, deterministic)
}
func (m *ReplyReserveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyReserveInfo.Merge(m, src)
}
func (m *ReplyReserveInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyReserveInfo.Size(m)
}
func (m *ReplyReserveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyReserveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyReserveInfo proto.InternalMessageInfo

func (m *ReplyReserveInfo) GetInfo() *ReserveInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyReserveInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyReserveList struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint64         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32         `protobuf:"varint,3,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32         `protobuf:"varint,4,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*ReserveInfo `protobuf:"bytes,21,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyReserveList) Reset()         { *m = ReplyReserveList{} }
func (m *ReplyReserveList) String() string { return proto.CompactTextString(m) }
func (*ReplyReserveList) ProtoMessage()    {}
func (*ReplyReserveList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec66a507dd698ded, []int{3}
}

func (m *ReplyReserveList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyReserveList.Unmarshal(m, b)
}
func (m *ReplyReserveList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyReserveList.Marshal(b, m, deterministic)
}
func (m *ReplyReserveList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyReserveList.Merge(m, src)
}
func (m *ReplyReserveList) XXX_Size() int {
	return xxx_messageInfo_ReplyReserveList.Size(m)
}
func (m *ReplyReserveList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyReserveList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyReserveList proto.InternalMessageInfo

func (m *ReplyReserveList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyReserveList) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyReserveList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyReserveList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyReserveList) GetList() []*ReserveInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*ReserveInfo)(nil), "omo.msp.third.ReserveInfo")
	proto.RegisterType((*ReqReserveAdd)(nil), "omo.msp.third.ReqReserveAdd")
	proto.RegisterType((*ReplyReserveInfo)(nil), "omo.msp.third.ReplyReserveInfo")
	proto.RegisterType((*ReplyReserveList)(nil), "omo.msp.third.ReplyReserveList")
}

func init() {
	proto.RegisterFile("proto/third/reserve.proto", fileDescriptor_ec66a507dd698ded)
}

var fileDescriptor_ec66a507dd698ded = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcf, 0x4e, 0x1b, 0x3f,
	0x10, 0x66, 0xb3, 0x21, 0x10, 0x87, 0xcd, 0x8f, 0x9f, 0xd5, 0x56, 0x6e, 0xd4, 0xaa, 0x51, 0x4e,
	0x39, 0x05, 0x89, 0x3e, 0x01, 0x54, 0x6a, 0x44, 0x55, 0xa8, 0xb4, 0xa8, 0x97, 0xde, 0x96, 0xf5,
	0x40, 0x2d, 0xb2, 0xeb, 0xc5, 0x76, 0x42, 0xf3, 0x50, 0x3d, 0xf5, 0x05, 0xfa, 0x10, 0x7d, 0xa0,
	0x6a, 0xc6, 0x9b, 0xd4, 0x81, 0x40, 0x72, 0x9b, 0x6f, 0xe6, 0x9b, 0x7f, 0xdf, 0x78, 0x13, 0xf6,
	0xba, 0x32, 0xda, 0xe9, 0x23, 0xf7, 0x5d, 0x19, 0x79, 0x64, 0xc0, 0x82, 0x99, 0xc1, 0x88, 0x7c,
	0x3c, 0xd1, 0x85, 0x1e, 0x15, 0xb6, 0x1a, 0x51, 0xb0, 0x27, 0x42, 0x66, 0xae, 0x8b, 0x42, 0x97,
	0x9e, 0x38, 0xf8, 0x15, 0xb3, 0x4e, 0xea, 0x53, 0xcf, 0xca, 0x6b, 0xcd, 0x0f, 0x59, 0x3c, 0x55,
	0x52, 0x44, 0xfd, 0x68, 0xd8, 0x4e, 0xd1, 0xe4, 0x5d, 0xd6, 0x50, 0x52, 0x34, 0xfa, 0xd1, 0xb0,
	0x99, 0x36, 0x94, 0xe4, 0x82, 0xed, 0xe5, 0x06, 0x32, 0x07, 0x52, 0xc4, 0xfd, 0x68, 0x18, 0xa7,
	0x0b, 0x88, 0x91, 0x69, 0x25, 0x29, 0xd2, 0xf4, 0x91, 0x1a, 0x2e, 0x73, 0xb4, 0x11, 0xbb, 0x54,
	0x79, 0x01, 0x79, 0x8f, 0xed, 0xeb, 0x0a, 0x0c, 0x85, 0x5a, 0x14, 0x5a, 0x62, 0xce, 0x59, 0xb3,
	0xcc, 0x0a, 0x10, 0x7b, 0xe4, 0x27, 0x9b, 0xbf, 0x62, 0x2d, 0x03, 0x45, 0x66, 0x6e, 0xc5, 0x3e,
	0x79, 0x6b, 0xc4, 0x5f, 0xb0, 0x5d, 0x9b, 0x43, 0x09, 0xa2, 0x4d, 0x6e, 0x0f, 0xa8, 0xaf, 0x2e,
	0x5d, 0x96, 0x3b, 0xc1, 0xea, 0xbe, 0x1e, 0x22, 0x3f, 0xd7, 0xd3, 0xd2, 0x89, 0x4e, 0x3f, 0x1a,
	0x26, 0xa9, 0x07, 0xd8, 0x11, 0x07, 0x16, 0x07, 0xbe, 0x23, 0xda, 0xe8, 0x73, 0xf3, 0x0a, 0x44,
	0x42, 0x44, 0xb2, 0x71, 0x0a, 0xeb, 0x32, 0x37, 0xb5, 0xa2, 0x4b, 0xde, 0x1a, 0x21, 0x77, 0xaa,
	0x4a, 0x27, 0xfe, 0xf3, 0xf9, 0x68, 0x63, 0xa7, 0x2b, 0xb8, 0x51, 0xa5, 0x38, 0xf4, 0x9d, 0x08,
	0xa0, 0xce, 0x50, 0x4a, 0xf1, 0x3f, 0xf9, 0xd0, 0xc4, 0xdc, 0x3c, 0x33, 0x52, 0x70, 0x9f, 0x8b,
	0x36, 0xf6, 0xc9, 0xac, 0x05, 0x67, 0xc5, 0xcb, 0x7e, 0x8c, 0xdb, 0x7a, 0x34, 0xf8, 0xd9, 0x60,
	0x49, 0x0a, 0x77, 0xf5, 0xe1, 0x4e, 0xa4, 0x5c, 0x6a, 0x15, 0xad, 0xd5, 0xaa, 0xb1, 0xa2, 0x55,
	0xa0, 0x4a, 0xbc, 0xaa, 0x4a, 0x78, 0x8d, 0xe6, 0x83, 0x6b, 0x2c, 0x15, 0xde, 0x0d, 0x15, 0xe6,
	0xac, 0x79, 0xab, 0x4a, 0x49, 0xb7, 0x4b, 0x52, 0xb2, 0xff, 0x69, 0xbb, 0xf7, 0x40, 0x5b, 0xd2,
	0x66, 0x3f, 0xd0, 0x66, 0xa1, 0x77, 0x3b, 0xd0, 0x7b, 0xa9, 0x17, 0x5b, 0xa3, 0x57, 0xe7, 0xb1,
	0x5e, 0x07, 0x5b, 0xe8, 0x35, 0x63, 0x87, 0x29, 0x54, 0x93, 0x79, 0xf8, 0xd2, 0x47, 0xac, 0xa9,
	0xca, 0x6b, 0x4d, 0x8a, 0x75, 0x8e, 0x7b, 0xa3, 0x95, 0x2f, 0x66, 0x14, 0x30, 0x53, 0xe2, 0xf1,
	0xe3, 0xe5, 0xcd, 0x1b, 0x4f, 0x64, 0x54, 0x93, 0xf9, 0x25, 0x31, 0x16, 0xef, 0x61, 0xf0, 0x3b,
	0x5a, 0x6d, 0xfc, 0x59, 0x59, 0x17, 0x14, 0x8a, 0xb6, 0x2d, 0x84, 0xa2, 0x38, 0xed, 0xb2, 0x49,
	0xfd, 0x1d, 0x7a, 0x80, 0x87, 0xac, 0xb2, 0x1b, 0x38, 0xcf, 0x7e, 0xd0, 0x21, 0x93, 0x74, 0x01,
	0x17, 0x91, 0x0b, 0x7d, 0x4f, 0x77, 0xac, 0x23, 0x17, 0xfa, 0x1e, 0xd7, 0x9e, 0x28, 0xeb, 0x48,
	0xa0, 0x0d, 0x6b, 0x23, 0xef, 0xf8, 0x4f, 0xcc, 0xba, 0xb5, 0xf7, 0x12, 0xcc, 0x4c, 0xe5, 0xc0,
	0xcf, 0x58, 0xeb, 0x44, 0xca, 0x2f, 0x25, 0xf0, 0x37, 0x8f, 0xd2, 0x83, 0x37, 0xd9, 0x7b, 0xb7,
	0x6e, 0xb1, 0xa0, 0xc3, 0x60, 0x87, 0x8f, 0x59, 0x6b, 0x0c, 0x0e, 0x4b, 0x3d, 0x9e, 0xe4, 0x6e,
	0x0a, 0xd6, 0x21, 0x6f, 0x9b, 0x42, 0x1f, 0x58, 0x3b, 0x85, 0x42, 0xcf, 0x60, 0x53, 0x2d, 0xb1,
	0xae, 0x56, 0x5d, 0xe4, 0x82, 0x75, 0xc6, 0xe0, 0x4e, 0xe7, 0x1f, 0xd5, 0xc4, 0x81, 0x59, 0xb7,
	0x1d, 0x96, 0xf1, 0xd1, 0x67, 0x87, 0xc2, 0x3b, 0x0f, 0x76, 0xf8, 0x39, 0x3b, 0x18, 0x83, 0xc3,
	0x53, 0x2a, 0xeb, 0x54, 0xbe, 0xa1, 0xe0, 0xdb, 0xa7, 0xde, 0x01, 0x25, 0x0f, 0x76, 0xf8, 0x27,
	0xd6, 0xfd, 0x4a, 0x3f, 0xa8, 0x9b, 0x26, 0xf4, 0xac, 0xe7, 0x56, 0x3d, 0x4d, 0xbe, 0x75, 0x82,
	0xff, 0x84, 0xab, 0x16, 0x81, 0xf7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xbd, 0xe6, 0x77,
	0x53, 0x06, 0x00, 0x00,
}
