// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/third/reserve.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReserveInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Scene                string   `protobuf:"bytes,9,opt,name=scene,proto3" json:"scene,omitempty"`
	Contact              string   `protobuf:"bytes,10,opt,name=contact,proto3" json:"contact,omitempty"`
	Count                uint32   `protobuf:"varint,11,opt,name=count,proto3" json:"count,omitempty"`
	Date                 string   `protobuf:"bytes,12,opt,name=date,proto3" json:"date,omitempty"`
	Type                 uint32   `protobuf:"varint,13,opt,name=type,proto3" json:"type,omitempty"`
	Status               uint32   `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveInfo) Reset()         { *m = ReserveInfo{} }
func (m *ReserveInfo) String() string { return proto.CompactTextString(m) }
func (*ReserveInfo) ProtoMessage()    {}
func (*ReserveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec66a507dd698ded, []int{0}
}

func (m *ReserveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveInfo.Unmarshal(m, b)
}
func (m *ReserveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveInfo.Marshal(b, m, deterministic)
}
func (m *ReserveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveInfo.Merge(m, src)
}
func (m *ReserveInfo) XXX_Size() int {
	return xxx_messageInfo_ReserveInfo.Size(m)
}
func (m *ReserveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveInfo proto.InternalMessageInfo

func (m *ReserveInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReserveInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReserveInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ReserveInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ReserveInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ReserveInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReserveInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReserveInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReserveInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReserveInfo) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *ReserveInfo) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReserveInfo) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ReserveInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReserveInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ReqReserveAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Contact              string   `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Scene                string   `protobuf:"bytes,5,opt,name=scene,proto3" json:"scene,omitempty"`
	Kind                 uint32   `protobuf:"varint,6,opt,name=kind,proto3" json:"kind,omitempty"`
	Count                uint32   `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqReserveAdd) Reset()         { *m = ReqReserveAdd{} }
func (m *ReqReserveAdd) String() string { return proto.CompactTextString(m) }
func (*ReqReserveAdd) ProtoMessage()    {}
func (*ReqReserveAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec66a507dd698ded, []int{1}
}

func (m *ReqReserveAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqReserveAdd.Unmarshal(m, b)
}
func (m *ReqReserveAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqReserveAdd.Marshal(b, m, deterministic)
}
func (m *ReqReserveAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqReserveAdd.Merge(m, src)
}
func (m *ReqReserveAdd) XXX_Size() int {
	return xxx_messageInfo_ReqReserveAdd.Size(m)
}
func (m *ReqReserveAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqReserveAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqReserveAdd proto.InternalMessageInfo

func (m *ReqReserveAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqReserveAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqReserveAdd) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *ReqReserveAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqReserveAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqReserveAdd) GetKind() uint32 {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *ReqReserveAdd) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReplyReserveInfo struct {
	Info                 *ReserveInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyReserveInfo) Reset()         { *m = ReplyReserveInfo{} }
func (m *ReplyReserveInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyReserveInfo) ProtoMessage()    {}
func (*ReplyReserveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec66a507dd698ded, []int{2}
}

func (m *ReplyReserveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyReserveInfo.Unmarshal(m, b)
}
func (m *ReplyReserveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyReserveInfo.Marshal(b, m, deterministic)
}
func (m *ReplyReserveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyReserveInfo.Merge(m, src)
}
func (m *ReplyReserveInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyReserveInfo.Size(m)
}
func (m *ReplyReserveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyReserveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyReserveInfo proto.InternalMessageInfo

func (m *ReplyReserveInfo) GetInfo() *ReserveInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyReserveInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyReserveList struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint64         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32         `protobuf:"varint,3,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32         `protobuf:"varint,4,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*ReserveInfo `protobuf:"bytes,21,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyReserveList) Reset()         { *m = ReplyReserveList{} }
func (m *ReplyReserveList) String() string { return proto.CompactTextString(m) }
func (*ReplyReserveList) ProtoMessage()    {}
func (*ReplyReserveList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec66a507dd698ded, []int{3}
}

func (m *ReplyReserveList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyReserveList.Unmarshal(m, b)
}
func (m *ReplyReserveList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyReserveList.Marshal(b, m, deterministic)
}
func (m *ReplyReserveList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyReserveList.Merge(m, src)
}
func (m *ReplyReserveList) XXX_Size() int {
	return xxx_messageInfo_ReplyReserveList.Size(m)
}
func (m *ReplyReserveList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyReserveList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyReserveList proto.InternalMessageInfo

func (m *ReplyReserveList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyReserveList) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyReserveList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyReserveList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyReserveList) GetList() []*ReserveInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*ReserveInfo)(nil), "omo.msp.third.ReserveInfo")
	proto.RegisterType((*ReqReserveAdd)(nil), "omo.msp.third.ReqReserveAdd")
	proto.RegisterType((*ReplyReserveInfo)(nil), "omo.msp.third.ReplyReserveInfo")
	proto.RegisterType((*ReplyReserveList)(nil), "omo.msp.third.ReplyReserveList")
}

func init() {
	proto.RegisterFile("proto/third/reserve.proto", fileDescriptor_ec66a507dd698ded)
}

var fileDescriptor_ec66a507dd698ded = []byte{
	// 554 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x7f, 0x92, 0x34, 0x9b, 0x3a, 0xaa, 0x56, 0x80, 0x96, 0x08, 0x44, 0xe4, 0x53, 0x4e,
	0xae, 0x14, 0x9e, 0xa0, 0x45, 0x22, 0x2a, 0xa2, 0x41, 0xda, 0x8a, 0x0b, 0x37, 0xe3, 0x9d, 0xc2,
	0xaa, 0xb1, 0xd7, 0x5d, 0x6f, 0x52, 0xf2, 0x58, 0xbc, 0x01, 0x77, 0xae, 0x3c, 0x10, 0xda, 0xb1,
	0x63, 0x36, 0x34, 0x6d, 0x7a, 0xdb, 0x6f, 0xe6, 0x9b, 0x6f, 0xe6, 0x1b, 0x8f, 0x4c, 0x5e, 0x96,
	0x5a, 0x19, 0x75, 0x6a, 0xbe, 0x4b, 0x2d, 0x4e, 0x35, 0x54, 0xa0, 0xd7, 0x90, 0x60, 0x8c, 0x46,
	0x2a, 0x57, 0x49, 0x5e, 0x95, 0x09, 0x26, 0xc7, 0xcc, 0x65, 0x66, 0x2a, 0xcf, 0x55, 0x51, 0x13,
	0xe3, 0xdf, 0x3e, 0x19, 0xf2, 0xba, 0xf4, 0xa2, 0xb8, 0x56, 0xf4, 0x84, 0x04, 0x2b, 0x29, 0x98,
	0x37, 0xf1, 0xa6, 0x03, 0x6e, 0x9f, 0x74, 0x44, 0x7c, 0x29, 0x98, 0x3f, 0xf1, 0xa6, 0x21, 0xf7,
	0xa5, 0xa0, 0x8c, 0xf4, 0x33, 0x0d, 0xa9, 0x01, 0xc1, 0x82, 0x89, 0x37, 0x0d, 0xf8, 0x16, 0xda,
	0xcc, 0xaa, 0x14, 0x98, 0x09, 0xeb, 0x4c, 0x03, 0xdb, 0x1a, 0xa5, 0x59, 0x17, 0x95, 0xb7, 0x90,
	0x8e, 0xc9, 0x91, 0x2a, 0x41, 0x63, 0xaa, 0x87, 0xa9, 0x16, 0x53, 0x4a, 0xc2, 0x22, 0xcd, 0x81,
	0xf5, 0x31, 0x8e, 0x6f, 0xfa, 0x82, 0xf4, 0x34, 0xe4, 0xa9, 0xbe, 0x61, 0x47, 0x18, 0x6d, 0x10,
	0x7d, 0x46, 0xba, 0x55, 0x06, 0x05, 0xb0, 0x01, 0x86, 0x6b, 0x80, 0x7d, 0x55, 0x61, 0xd2, 0xcc,
	0x30, 0xd2, 0xf4, 0xad, 0xa1, 0xe5, 0x67, 0x6a, 0x55, 0x18, 0x36, 0x9c, 0x78, 0xd3, 0x88, 0xd7,
	0xc0, 0x76, 0xb4, 0x03, 0xb3, 0xe3, 0xba, 0xa3, 0x7d, 0xdb, 0x98, 0xd9, 0x94, 0xc0, 0x22, 0x24,
	0xe2, 0xdb, 0x4e, 0x51, 0x99, 0xd4, 0xac, 0x2a, 0x36, 0xc2, 0x68, 0x83, 0xe2, 0x9f, 0x1e, 0x89,
	0x38, 0xdc, 0x36, 0x0b, 0x3d, 0x13, 0xa2, 0xf5, 0xe0, 0xed, 0xf5, 0xe0, 0xef, 0x78, 0x70, 0xa6,
	0x0d, 0x76, 0xa7, 0x75, 0xb7, 0x14, 0xfe, 0xb7, 0xa5, 0xd6, 0x79, 0xd7, 0x75, 0x4e, 0x49, 0x78,
	0x23, 0x0b, 0x81, 0x3b, 0x8d, 0x38, 0xbe, 0xff, 0x79, 0xee, 0x3b, 0x9e, 0xe3, 0x35, 0x39, 0xe1,
	0x50, 0x2e, 0x37, 0xee, 0x15, 0x24, 0x24, 0x94, 0xc5, 0xb5, 0xc2, 0xa9, 0x87, 0xb3, 0x71, 0xb2,
	0x73, 0x4d, 0x89, 0xc3, 0xe4, 0xc8, 0xa3, 0xb3, 0x76, 0x1f, 0xfe, 0x03, 0x15, 0xe5, 0x72, 0x73,
	0x85, 0x8c, 0x76, 0x57, 0xbf, 0xbc, 0xdd, 0xc6, 0x1f, 0x65, 0x65, 0x1c, 0x21, 0xef, 0xa9, 0x42,
	0xd6, 0x96, 0x51, 0x26, 0x5d, 0x36, 0x37, 0x5a, 0x03, 0xbb, 0xcc, 0x32, 0xfd, 0x06, 0x97, 0xe9,
	0x0f, 0x5c, 0x66, 0xc4, 0xb7, 0x70, 0x9b, 0x59, 0xa8, 0x3b, 0xdc, 0x65, 0x93, 0x59, 0xa8, 0x3b,
	0x6b, 0x7b, 0x29, 0x2b, 0xc3, 0x9e, 0x4f, 0x82, 0x43, 0xb6, 0x2d, 0x6f, 0xf6, 0x27, 0x20, 0xa3,
	0x26, 0x7a, 0x05, 0x7a, 0x2d, 0x33, 0xa0, 0x17, 0xa4, 0x77, 0x26, 0xc4, 0xa7, 0x02, 0xe8, 0xab,
	0x7b, 0xe5, 0xce, 0x5d, 0x8c, 0xdf, 0xec, 0x33, 0xe6, 0x74, 0x88, 0x3b, 0x74, 0x4e, 0x7a, 0x73,
	0x30, 0x56, 0xea, 0xfe, 0x24, 0xb7, 0x2b, 0xa8, 0x8c, 0xe5, 0x3d, 0x45, 0xe8, 0x1d, 0x19, 0x70,
	0xc8, 0xd5, 0x1a, 0x0e, 0x69, 0xb1, 0x7d, 0x5a, 0x8d, 0xc8, 0x82, 0x0c, 0xe7, 0x60, 0xce, 0x37,
	0xef, 0xe5, 0xd2, 0x80, 0xde, 0xe7, 0xce, 0xca, 0xd4, 0xd9, 0x47, 0x87, 0xb2, 0xdf, 0x39, 0xee,
	0xd0, 0x4b, 0x72, 0x3c, 0x07, 0x63, 0x3f, 0xa5, 0xac, 0x8c, 0xcc, 0x0e, 0x08, 0xbe, 0x7e, 0xe8,
	0x0e, 0xb0, 0x38, 0xee, 0xd0, 0x0f, 0x64, 0xf4, 0x19, 0x7f, 0x36, 0x87, 0x26, 0xac, 0x59, 0x8f,
	0x59, 0x3d, 0x8f, 0xbe, 0x0c, 0x9d, 0xff, 0xe5, 0xd7, 0x1e, 0x82, 0xb7, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x80, 0x07, 0xa1, 0xed, 0x6f, 0x05, 0x00, 0x00,
}
