// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/third/schedule.proto

package third

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScheduleInfo struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 uint32        `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Created              int64         `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64         `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string        `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string        `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string        `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string        `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string        `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	Status               uint32        `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	Sheet                string        `protobuf:"bytes,12,opt,name=sheet,proto3" json:"sheet,omitempty"`
	Color                string        `protobuf:"bytes,13,opt,name=color,proto3" json:"color,omitempty"`
	Ignore               uint32        `protobuf:"varint,14,opt,name=ignore,proto3" json:"ignore,omitempty"`
	Date                 *DurationInfo `protobuf:"bytes,21,opt,name=date,proto3" json:"date,omitempty"`
	Time                 *DurationInfo `protobuf:"bytes,22,opt,name=time,proto3" json:"time,omitempty"`
	Weekdays             []uint32      `protobuf:"varint,30,rep,packed,name=weekdays,proto3" json:"weekdays,omitempty"`
	Targets              []string      `protobuf:"bytes,31,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ScheduleInfo) Reset()         { *m = ScheduleInfo{} }
func (m *ScheduleInfo) String() string { return proto.CompactTextString(m) }
func (*ScheduleInfo) ProtoMessage()    {}
func (*ScheduleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7f93fa7d0faaba, []int{0}
}

func (m *ScheduleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleInfo.Unmarshal(m, b)
}
func (m *ScheduleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleInfo.Marshal(b, m, deterministic)
}
func (m *ScheduleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleInfo.Merge(m, src)
}
func (m *ScheduleInfo) XXX_Size() int {
	return xxx_messageInfo_ScheduleInfo.Size(m)
}
func (m *ScheduleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleInfo proto.InternalMessageInfo

func (m *ScheduleInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ScheduleInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ScheduleInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ScheduleInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ScheduleInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ScheduleInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ScheduleInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ScheduleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScheduleInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ScheduleInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ScheduleInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ScheduleInfo) GetSheet() string {
	if m != nil {
		return m.Sheet
	}
	return ""
}

func (m *ScheduleInfo) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *ScheduleInfo) GetIgnore() uint32 {
	if m != nil {
		return m.Ignore
	}
	return 0
}

func (m *ScheduleInfo) GetDate() *DurationInfo {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ScheduleInfo) GetTime() *DurationInfo {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *ScheduleInfo) GetWeekdays() []uint32 {
	if m != nil {
		return m.Weekdays
	}
	return nil
}

func (m *ScheduleInfo) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

type DurationInfo struct {
	Begin                int64    `protobuf:"varint,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DurationInfo) Reset()         { *m = DurationInfo{} }
func (m *DurationInfo) String() string { return proto.CompactTextString(m) }
func (*DurationInfo) ProtoMessage()    {}
func (*DurationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7f93fa7d0faaba, []int{1}
}

func (m *DurationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DurationInfo.Unmarshal(m, b)
}
func (m *DurationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DurationInfo.Marshal(b, m, deterministic)
}
func (m *DurationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DurationInfo.Merge(m, src)
}
func (m *DurationInfo) XXX_Size() int {
	return xxx_messageInfo_DurationInfo.Size(m)
}
func (m *DurationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DurationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DurationInfo proto.InternalMessageInfo

func (m *DurationInfo) GetBegin() int64 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *DurationInfo) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type ReqScheduleAdd struct {
	Uid                  string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string        `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string        `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Operator             string        `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Sheet                string        `protobuf:"bytes,6,opt,name=sheet,proto3" json:"sheet,omitempty"`
	Color                string        `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Ignore               uint32        `protobuf:"varint,8,opt,name=ignore,proto3" json:"ignore,omitempty"`
	Type                 uint32        `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	Date                 *DurationInfo `protobuf:"bytes,11,opt,name=date,proto3" json:"date,omitempty"`
	Time                 *DurationInfo `protobuf:"bytes,12,opt,name=time,proto3" json:"time,omitempty"`
	Targets              []string      `protobuf:"bytes,15,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqScheduleAdd) Reset()         { *m = ReqScheduleAdd{} }
func (m *ReqScheduleAdd) String() string { return proto.CompactTextString(m) }
func (*ReqScheduleAdd) ProtoMessage()    {}
func (*ReqScheduleAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7f93fa7d0faaba, []int{2}
}

func (m *ReqScheduleAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqScheduleAdd.Unmarshal(m, b)
}
func (m *ReqScheduleAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqScheduleAdd.Marshal(b, m, deterministic)
}
func (m *ReqScheduleAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqScheduleAdd.Merge(m, src)
}
func (m *ReqScheduleAdd) XXX_Size() int {
	return xxx_messageInfo_ReqScheduleAdd.Size(m)
}
func (m *ReqScheduleAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqScheduleAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqScheduleAdd proto.InternalMessageInfo

func (m *ReqScheduleAdd) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqScheduleAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqScheduleAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqScheduleAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqScheduleAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqScheduleAdd) GetSheet() string {
	if m != nil {
		return m.Sheet
	}
	return ""
}

func (m *ReqScheduleAdd) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *ReqScheduleAdd) GetIgnore() uint32 {
	if m != nil {
		return m.Ignore
	}
	return 0
}

func (m *ReqScheduleAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqScheduleAdd) GetDate() *DurationInfo {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *ReqScheduleAdd) GetTime() *DurationInfo {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *ReqScheduleAdd) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

type ReplyScheduleInfo struct {
	Status               *ReplyStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *ScheduleInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyScheduleInfo) Reset()         { *m = ReplyScheduleInfo{} }
func (m *ReplyScheduleInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyScheduleInfo) ProtoMessage()    {}
func (*ReplyScheduleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7f93fa7d0faaba, []int{3}
}

func (m *ReplyScheduleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyScheduleInfo.Unmarshal(m, b)
}
func (m *ReplyScheduleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyScheduleInfo.Marshal(b, m, deterministic)
}
func (m *ReplyScheduleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyScheduleInfo.Merge(m, src)
}
func (m *ReplyScheduleInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyScheduleInfo.Size(m)
}
func (m *ReplyScheduleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyScheduleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyScheduleInfo proto.InternalMessageInfo

func (m *ReplyScheduleInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyScheduleInfo) GetInfo() *ScheduleInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyScheduleList struct {
	Status               *ReplyStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32          `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32          `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32          `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*ScheduleInfo `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReplyScheduleList) Reset()         { *m = ReplyScheduleList{} }
func (m *ReplyScheduleList) String() string { return proto.CompactTextString(m) }
func (*ReplyScheduleList) ProtoMessage()    {}
func (*ReplyScheduleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa7f93fa7d0faaba, []int{4}
}

func (m *ReplyScheduleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyScheduleList.Unmarshal(m, b)
}
func (m *ReplyScheduleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyScheduleList.Marshal(b, m, deterministic)
}
func (m *ReplyScheduleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyScheduleList.Merge(m, src)
}
func (m *ReplyScheduleList) XXX_Size() int {
	return xxx_messageInfo_ReplyScheduleList.Size(m)
}
func (m *ReplyScheduleList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyScheduleList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyScheduleList proto.InternalMessageInfo

func (m *ReplyScheduleList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyScheduleList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyScheduleList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyScheduleList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyScheduleList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyScheduleList) GetList() []*ScheduleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*ScheduleInfo)(nil), "omo.msp.third.ScheduleInfo")
	proto.RegisterType((*DurationInfo)(nil), "omo.msp.third.DurationInfo")
	proto.RegisterType((*ReqScheduleAdd)(nil), "omo.msp.third.ReqScheduleAdd")
	proto.RegisterType((*ReplyScheduleInfo)(nil), "omo.msp.third.ReplyScheduleInfo")
	proto.RegisterType((*ReplyScheduleList)(nil), "omo.msp.third.ReplyScheduleList")
}

func init() {
	proto.RegisterFile("proto/third/schedule.proto", fileDescriptor_fa7f93fa7d0faaba)
}

var fileDescriptor_fa7f93fa7d0faaba = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0xc7, 0x71, 0x9c, 0x04, 0xb2, 0x89, 0x03, 0x5d, 0x51, 0xb4, 0x4a, 0x4b, 0x6b, 0xf9, 0x94,
	0x53, 0x22, 0x51, 0xa9, 0x77, 0x68, 0x55, 0xfa, 0x29, 0xa4, 0x45, 0xbd, 0xf4, 0x66, 0xe2, 0x21,
	0xac, 0x88, 0xbd, 0x66, 0xbd, 0x86, 0xe6, 0x2d, 0x7b, 0xe8, 0xa5, 0xf7, 0x3e, 0x48, 0x35, 0xbb,
	0xb6, 0xe5, 0x80, 0x4b, 0xd2, 0xde, 0xf6, 0x3f, 0x9f, 0x99, 0xf9, 0x0d, 0x86, 0x8c, 0x52, 0x25,
	0xb5, 0x9c, 0xea, 0x2b, 0xa1, 0xa2, 0x69, 0x36, 0xbb, 0x82, 0x28, 0x5f, 0xc0, 0xc4, 0x18, 0xa9,
	0x27, 0x63, 0x39, 0x89, 0xb3, 0x74, 0x62, 0xbc, 0x23, 0x56, 0x0f, 0x9d, 0xc9, 0x38, 0x96, 0x89,
	0x0d, 0x0c, 0x7e, 0xbb, 0x64, 0x70, 0x5e, 0xe4, 0x7e, 0x48, 0x2e, 0x25, 0xdd, 0x23, 0x6e, 0x2e,
	0x22, 0xe6, 0xf8, 0xce, 0xb8, 0xc7, 0xf1, 0x49, 0x87, 0xa4, 0x25, 0x22, 0xd6, 0xf2, 0x9d, 0x71,
	0x9b, 0xb7, 0x44, 0x44, 0x29, 0x69, 0xeb, 0x65, 0x0a, 0xcc, 0xf5, 0x9d, 0xb1, 0xc7, 0xcd, 0x9b,
	0x32, 0xb2, 0x3d, 0x53, 0x10, 0x6a, 0x88, 0x58, 0xdb, 0x77, 0xc6, 0x2e, 0x2f, 0x25, 0x7a, 0xf2,
	0x34, 0x32, 0x9e, 0x8e, 0xf5, 0x14, 0xb2, 0xca, 0x91, 0x8a, 0x75, 0x4d, 0xb7, 0x52, 0xd2, 0x11,
	0xd9, 0x91, 0x29, 0x28, 0xe3, 0xda, 0x36, 0xae, 0x4a, 0x63, 0xf7, 0x24, 0x8c, 0x81, 0xed, 0x18,
	0xbb, 0x79, 0xd3, 0x03, 0xd2, 0x55, 0x10, 0x87, 0xea, 0x9a, 0xf5, 0x8c, 0xb5, 0x50, 0x74, 0x9f,
	0x74, 0xe4, 0x5d, 0x02, 0x8a, 0x11, 0x63, 0xb6, 0x02, 0xa3, 0x33, 0x1d, 0xea, 0x3c, 0x63, 0x7d,
	0x33, 0x41, 0xa1, 0x30, 0x3a, 0xbb, 0x02, 0xd0, 0x6c, 0x60, 0xa3, 0x8d, 0x40, 0xeb, 0x4c, 0x2e,
	0xa4, 0x62, 0x9e, 0xb5, 0x1a, 0x81, 0x35, 0xc4, 0x3c, 0x91, 0x0a, 0xd8, 0xd0, 0xd6, 0xb0, 0x8a,
	0x4e, 0x49, 0x1b, 0x87, 0x63, 0x4f, 0x7d, 0x67, 0xdc, 0x3f, 0x7a, 0x36, 0x59, 0xc1, 0x30, 0x79,
	0x9b, 0xab, 0x50, 0x0b, 0x99, 0xe0, 0xa2, 0xb9, 0x09, 0xc4, 0x04, 0x2d, 0x62, 0x60, 0x07, 0x1b,
	0x24, 0x60, 0x20, 0xee, 0xe6, 0x0e, 0xe0, 0x3a, 0x0a, 0x97, 0x19, 0x7b, 0xe1, 0xbb, 0x63, 0x8f,
	0x57, 0x1a, 0x37, 0xaa, 0x43, 0x35, 0x07, 0x9d, 0xb1, 0x97, 0xbe, 0x8b, 0x1b, 0x2d, 0x64, 0xf0,
	0x9a, 0x0c, 0xea, 0xb5, 0x70, 0xaa, 0x0b, 0x98, 0x8b, 0xc4, 0x70, 0x76, 0xb9, 0x15, 0xc8, 0x1e,
	0x12, 0x8b, 0xda, 0xe5, 0xf8, 0x0c, 0x7e, 0xb6, 0xc8, 0x90, 0xc3, 0x4d, 0x79, 0x21, 0xc7, 0x51,
	0xd4, 0x70, 0x20, 0x25, 0x92, 0x56, 0x23, 0x12, 0xb7, 0x19, 0x49, 0xbb, 0x8e, 0xa4, 0x0e, 0xbc,
	0x73, 0x0f, 0x78, 0x85, 0xa5, 0xdb, 0x88, 0x65, 0xbb, 0x19, 0xcb, 0xce, 0x0a, 0x96, 0xf2, 0x64,
	0x7b, 0xb5, 0x93, 0x2d, 0x51, 0xf5, 0xff, 0x15, 0xd5, 0x60, 0x53, 0x54, 0x35, 0x1c, 0xbb, 0xab,
	0x38, 0xbe, 0x93, 0x27, 0x1c, 0xd2, 0xc5, 0x72, 0xe5, 0x2f, 0xef, 0xa8, 0xba, 0x4b, 0xc7, 0x74,
	0x18, 0xdd, 0xeb, 0x60, 0x33, 0x4c, 0x44, 0x75, 0xb3, 0x53, 0xd2, 0x16, 0xc9, 0xa5, 0x34, 0xab,
	0x7f, 0xf8, 0x9b, 0xea, 0xe5, 0xb9, 0x09, 0x0c, 0x7e, 0x38, 0xf7, 0x5a, 0x7f, 0x16, 0x99, 0xfe,
	0xaf, 0xd6, 0xfb, 0xa4, 0xa3, 0xa5, 0x0e, 0x17, 0xa6, 0xb7, 0xc7, 0xad, 0x40, 0x6b, 0x1a, 0xce,
	0x21, 0x2b, 0xbe, 0x0e, 0x56, 0xe0, 0xfe, 0xf1, 0x61, 0xa0, 0x7b, 0xdc, 0xbc, 0x91, 0x55, 0x92,
	0xc7, 0x17, 0x60, 0x89, 0x7b, 0xbc, 0x50, 0x38, 0xd2, 0x42, 0x64, 0x9a, 0xed, 0xf9, 0xee, 0xda,
	0x91, 0x30, 0xf0, 0xe8, 0x97, 0x4b, 0x76, 0x4b, 0xf3, 0x39, 0xa8, 0x5b, 0x31, 0x03, 0xfa, 0x89,
	0x74, 0x8f, 0xa3, 0xe8, 0x2c, 0x01, 0x7a, 0xf8, 0x60, 0x94, 0xfa, 0x35, 0x8f, 0xfc, 0xc6, 0x49,
	0x6b, 0x4d, 0x82, 0x2d, 0xfa, 0x9e, 0x74, 0x4f, 0x41, 0x63, 0xb1, 0x87, 0x7b, 0xb9, 0xc9, 0x21,
	0xd3, 0x18, 0xb7, 0x51, 0xa5, 0x33, 0xd2, 0x3f, 0x05, 0x7d, 0xb2, 0x7c, 0x27, 0x16, 0x1a, 0x14,
	0x7d, 0xde, 0x5c, 0xce, 0x7a, 0x1f, 0x2f, 0x88, 0xd8, 0x82, 0x2d, 0xfa, 0x85, 0x0c, 0x4e, 0x41,
	0x23, 0x19, 0x91, 0x69, 0x31, 0x5b, 0x53, 0xf1, 0xf0, 0x6f, 0x58, 0x4d, 0x72, 0xb0, 0x45, 0x3f,
	0x92, 0xe1, 0x57, 0xf3, 0x75, 0x5e, 0xf7, 0x13, 0x6d, 0xd4, 0x88, 0x35, 0x15, 0x2c, 0x66, 0x7d,
	0x43, 0x7a, 0x1c, 0x62, 0x79, 0x0b, 0xeb, 0x16, 0xf7, 0x48, 0x91, 0x13, 0xef, 0x5b, 0xbf, 0xf6,
	0xaf, 0xeb, 0xa2, 0x6b, 0xc4, 0xab, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x35, 0xa7, 0x82,
	0xfb, 0x06, 0x00, 0x00,
}
